CREATE TABLE ANEXOS_TIPO (
ANEX_TIPO_CODI           SMALLINT NOT NULL,
ANEX_TIPO_EXT            VARCHAR(10) NOT NULL,
ANEX_TIPO_DESC           VARCHAR(50) NULL,
                 PRIMARY KEY (ANEX_TIPO_CODI)
);
CREATE UNIQUE INDEX IDX_ANEX_TIPO_CODI ON ANEXOS_TIPO (ANEX_TIPO_CODI);
CREATE TABLE BODEGA_EMPRESAS (
NOMBRE_DE_LA_EMPRESA     VARCHAR(160) NULL,
NUIR                     VARCHAR(13) NULL,
NIT_DE_LA_EMPRESA        VARCHAR(80) NULL,
SIGLA_DE_LA_EMPRESA      VARCHAR(80) NULL,
DIRECCION                VARCHAR(80) NULL,
CODIGO_DEL_DEPARTAMENTO  SMALLINT NULL,
CODIGO_DEL_MUNICIPIO     SMALLINT NULL,
TELEFONO_1               VARCHAR(15) NULL,
TELEFONO_2               VARCHAR(15) NULL,
EMAIL                    VARCHAR(50) NULL,
NOMBRE_REP_LEGAL         VARCHAR(72) NULL,
CARGO_REP_LEGAL          VARCHAR(50) NULL,
IDENTIFICADOR_EMPRESA    INT NOT NULL,
ARE_ESP_SECUE            INT NOT NULL,
ID_CONT                  TINYINT DEFAULT 1,
ID_PAIS                  SMALLINT DEFAULT 170,
ACTIVA                   TINYINT DEFAULT 1,
FLAG_RUPS                VARCHAR(1) NULL,
                 PRIMARY KEY (IDENTIFICADOR_EMPRESA)
);
CREATE INDEX IDX_BODEGA_NOMBRE ON BODEGA_EMPRESAS (NOMBRE_DE_LA_EMPRESA);
CREATE INDEX IDX_BODEGA_NUIR ON BODEGA_EMPRESAS (NUIR);
CREATE INDEX IDX_BODEGA_NIT ON BODEGA_EMPRESAS (NIT_DE_LA_EMPRESA);
CREATE INDEX IDX_BODEGA_SIGLA ON BODEGA_EMPRESAS (SIGLA_DE_LA_EMPRESA);
CREATE INDEX IDX_BODEGA_INTER ON BODEGA_EMPRESAS (CODIGO_DEL_DEPARTAMENTO, CODIGO_DEL_MUNICIPIO, ID_CONT, ID_PAIS);
CREATE INDEX SGD_BODEGA_REP_LEGAL ON BODEGA_EMPRESAS (CARGO_REP_LEGAL);
CREATE INDEX IDX_BODEGA_EMPRESAS ON BODEGA_EMPRESAS (IDENTIFICADOR_EMPRESA);
CREATE INDEX SGD_BODEGA_ARE_ESP_SECUE ON BODEGA_EMPRESAS (ARE_ESP_SECUE);
CREATE TABLE CARPETA (
CARP_CODI                TINYINT NOT NULL,
CARP_DESC                VARCHAR(80) NOT NULL,
                 PRIMARY KEY (CARP_CODI)
);
CREATE UNIQUE INDEX IDX_CARPETAS ON CARPETA (CARP_CODI);
CREATE TABLE ESTADO (
ESTA_CODI                TINYINT NOT NULL,
ESTA_DESC                VARCHAR(100) NOT NULL,
                 PRIMARY KEY (ESTA_CODI)
);
CREATE UNIQUE INDEX IDX_ESTADO ON ESTADO (ESTA_CODI);
CREATE TABLE MEDIO_RECEPCION (
MREC_CODI                TINYINT NOT NULL,
MREC_DESC                VARCHAR(100) NOT NULL,
                 PRIMARY KEY (MREC_CODI)
);
CREATE UNIQUE INDEX IDX_MEDIO_RECEPCION ON MEDIO_RECEPCION (MREC_CODI);
CREATE TABLE PAR_SERV_SERVICIOS (
PAR_SERV_SECUE           INT NOT NULL,
PAR_SERV_CODIGO          VARCHAR(5) NULL,
PAR_SERV_NOMBRE          VARCHAR(100) NULL,
PAR_SERV_ESTADO          VARCHAR(1) NULL,
                 PRIMARY KEY (PAR_SERV_SECUE)
);
CREATE UNIQUE INDEX IDX_PAR_SERV_SERVICIOS ON PAR_SERV_SERVICIOS (PAR_SERV_SECUE);
CREATE TABLE SERIES (
DEPE_CODI                INT NOT NULL,
SERI_NUME                INT NOT NULL,
SERI_TIPO                TINYINT NOT NULL,
SERI_ANO                 SMALLINT NOT NULL,
DPTO_CODI                SMALLINT NOT NULL,
BLOQ                     VARCHAR(20) NULL,
                 PRIMARY KEY (DEPE_CODI, SERI_TIPO, SERI_ANO)
);
CREATE UNIQUE INDEX IDX_SERIES ON SERIES (DEPE_CODI, SERI_TIPO, SERI_ANO);
CREATE INDEX IDX_BLOQUEO ON SERIES (BLOQ);
CREATE TABLE SGD_ADMIN_DEPENDENCIA_ESTADO (
CODIGO_ESTADO            BIGINT NOT NULL,
DESCRIPCION_ESTADO       VARCHAR(50) NOT NULL,
                 PRIMARY KEY (CODIGO_ESTADO)
);
CREATE TABLE SGD_ADMIN_OBSERVACION (
CODIGO_OBSERVACION       BIGINT NOT NULL,
DESCRIPCION_OBSERVACION  VARCHAR(500) NOT NULL,
                 PRIMARY KEY (CODIGO_OBSERVACION)
);
CREATE TABLE SGD_ADMIN_USUA_PERFILES (
CODIGO_PERFIL            BIGINT NOT NULL,
DESCRIPCION_PERFIL       VARCHAR(200) NOT NULL,
                 PRIMARY KEY (CODIGO_PERFIL)
);
CREATE TABLE SGD_APLI_APLINTEGRA (
SGD_APLI_CODI            SMALLINT NOT NULL,
SGD_APLI_DESCRIP         VARCHAR(150) NULL,
SGD_APLI_LK1DESC         VARCHAR(150) NULL,
SGD_APLI_LK1             VARCHAR(150) NULL,
SGD_APLI_LK2DESC         VARCHAR(150) NULL,
SGD_APLI_LK2             VARCHAR(150) NULL,
SGD_APLI_LK3DESC         VARCHAR(150) NULL,
SGD_APLI_LK3             VARCHAR(150) NULL,
SGD_APLI_LK4DESC         VARCHAR(150) NULL,
SGD_APLI_LK4             VARCHAR(150) NULL,
                 PRIMARY KEY (SGD_APLI_CODI)
);
CREATE UNIQUE INDEX IDX_SGD_APLI_APLINTEGRA ON SGD_APLI_APLINTEGRA (SGD_APLI_CODI);
CREATE TABLE SGD_ARGD_ARGDOC (
SGD_ARGD_CODI            SMALLINT NOT NULL,
SGD_PNUFE_CODI           SMALLINT NULL,
SGD_ARGD_TABLA           VARCHAR(100) NULL,
SGD_ARGD_TCODI           VARCHAR(100) NULL,
SGD_ARGD_TDES            VARCHAR(100) NULL,
SGD_ARGD_LLIST           VARCHAR(150) NULL,
SGD_ARGD_CAMPO           VARCHAR(100) NULL,
                 PRIMARY KEY (SGD_ARGD_CODI)
);
CREATE UNIQUE INDEX IDX_SGD_ARGD_ARGDOC ON SGD_ARGD_ARGDOC (SGD_ARGD_CODI);
CREATE TABLE SGD_CAU_CAUSAL (
SGD_CAU_CODIGO           SMALLINT NOT NULL,
SGD_CAU_DESCRIP          VARCHAR(150) NULL,
                 PRIMARY KEY (SGD_CAU_CODIGO)
);
CREATE UNIQUE INDEX IDX_SGD_CAU_CAUSAL ON SGD_CAU_CAUSAL (SGD_CAU_CODIGO);
CREATE TABLE SGD_EINV_INVENTARIO (
SGD_EINV_CODIGO          INT NOT NULL,
SGD_DEPE_NOMB            VARCHAR(400) NULL,
SGD_DEPE_CODI            INT NULL,
SGD_EINV_EXPNUM          VARCHAR(18) NULL,
SGD_EINV_TITULO          VARCHAR(400) NULL,
SGD_EINV_UNIDAD          INT NULL,
SGD_EINV_FECH            DATETIME NULL,
SGD_EINV_FECHFIN         DATETIME NULL,
SGD_EINV_RADICADOS       VARCHAR(40) NULL,
SGD_EINV_FOLIOS          INT NULL,
SGD_EINV_NUNDOCU         INT NULL,
SGD_EINV_NUNDOCUBODEGA   INT NULL,
SGD_EINV_CAJA            INT NULL,
SGD_EINV_CAJABODEGA      INT NULL,
SGD_EINV_SRD             INT NULL,
SGD_EINV_NOMSRD          VARCHAR(400) NULL,
SGD_EINV_SBRD            INT NULL,
SGD_EINV_NOMSBRD         VARCHAR(400) NULL,
SGD_EINV_RETENCION       VARCHAR(400) NULL,
SGD_EINV_DISFINAL        VARCHAR(400) NULL,
SGD_EINV_UBICACION       VARCHAR(400) NULL,
SGD_EINV_OBSERVACION     VARCHAR(400) NULL,
                 PRIMARY KEY (SGD_EINV_CODIGO)
);
CREATE UNIQUE INDEX IDX_EINV_INVENTARIO ON SGD_EINV_INVENTARIO (SGD_EINV_CODIGO);
CREATE TABLE SGD_EIT_ITEMS (
SGD_EIT_CODIGO           INT NOT NULL,
SGD_EIT_PISO             VARCHAR(4) DEFAULT '0',
SGD_EIT_PISONOM          VARCHAR(40) NULL,
SGD_EIT_ARCHIVADOR       VARCHAR(4) NULL,
SGD_EIT_ITEMSO           VARCHAR(40) NULL,
SGD_EIT_ITEMSN           VARCHAR(40) NULL,
SGD_EIT_ESTANTE          SMALLINT NULL,
SGD_EIT_CAJAS            INT NULL,
SGD_EIT_CAPTOL           SMALLINT NULL,
SGD_EIT_EDIFICIO         VARCHAR(400) NULL,
SGD_EIT_ZONA             VARCHAR(40) NULL,
SGD_EIT_DPTO             VARCHAR(400) NULL,
SGD_EIT_MUNI             VARCHAR(400) NULL,
                 PRIMARY KEY (SGD_EIT_CODIGO)
);
CREATE UNIQUE INDEX IDX_EIT_ITEMS ON SGD_EIT_ITEMS (SGD_EIT_CODIGO);
CREATE TABLE SGD_FUN_FUNCIONES (
SGD_FUN_CODIGO           SMALLINT NOT NULL,
SGD_FUN_DESCRIP          VARCHAR(530) NULL,
SGD_FUN_FECH_INI         DATETIME NULL,
SGD_FUN_FECH_FIN         DATETIME NULL,
                 PRIMARY KEY (SGD_FUN_CODIGO)
);
CREATE UNIQUE INDEX IDX_FUN_FUNCIONES ON SGD_FUN_FUNCIONES (SGD_FUN_CODIGO);
CREATE TABLE SGD_INSTORF_INSTANCIASORFEO (
SGD_INSTORF_CODI         SMALLINT NOT NULL,
SGD_INSTORF_DESC         VARCHAR(100) NULL,
                 PRIMARY KEY (SGD_INSTORF_CODI)
);
CREATE UNIQUE INDEX IDX_INSTORF_INSTANCIASORFEO ON SGD_INSTORF_INSTANCIASORFEO (SGD_INSTORF_CODI);
CREATE TABLE SGD_MASIVA_EXCEL (
SGD_MASIVA_DEPENDENCIA   SMALLINT NULL,
SGD_MASIVA_USUARIO       BIGINT NULL,
SGD_MASIVA_TIPORADICACION TINYINT NULL,
SGD_MASIVA_CODIGO        BIGINT NOT NULL,
SGD_MASIVA_RADICADA      TINYINT NULL,
SGD_MASIVA_INTERVALO     SMALLINT NULL,
SGD_MASIVA_RANGOINI      VARCHAR(15) NULL,
SGD_MASIVA_RANGOFIN      VARCHAR(15) NULL,
                 PRIMARY KEY (SGD_MASIVA_CODIGO)
);
CREATE UNIQUE INDEX SGD_MASIVA_CODIGO ON SGD_MASIVA_EXCEL (SGD_MASIVA_CODIGO);
CREATE TABLE SGD_NOT_NOTIFICACION (
SGD_NOT_CODI             SMALLINT NOT NULL,
SGD_NOT_DESCRIP          VARCHAR(100) NOT NULL,
                 PRIMARY KEY (SGD_NOT_CODI)
);
CREATE UNIQUE INDEX IDX_SGD_NOT ON SGD_NOT_NOTIFICACION (SGD_NOT_CODI);
CREATE TABLE SGD_PARAMETRO (
PARAM_NOMB               VARCHAR(25) NOT NULL,
PARAM_CODI               INT NOT NULL,
PARAM_VALOR              VARCHAR(25) NOT NULL,
                 PRIMARY KEY (PARAM_NOMB, PARAM_CODI)
);
CREATE UNIQUE INDEX IDX_PARAMETRO_PK ON SGD_PARAMETRO (PARAM_NOMB, PARAM_CODI);
CREATE TABLE SGD_PRC_PROCESO (
SGD_PRC_CODIGO           SMALLINT NOT NULL,
SGD_PRC_DESCRIP          VARCHAR(150) NULL,
SGD_PRC_FECH_INI         DATETIME NULL,
SGD_PRC_FECH_FIN         DATETIME NULL,
                 PRIMARY KEY (SGD_PRC_CODIGO)
);
CREATE UNIQUE INDEX IDX_PRC_PROCESO ON SGD_PRC_PROCESO (SGD_PRC_CODIGO);
CREATE TABLE SGD_RFAX_RESERVAFAX (
SGD_RFAX_CODIGO          BIGINT NULL,
SGD_RFAX_FAX             VARCHAR(30) NULL,
USUA_LOGIN               VARCHAR(30) NULL,
SGD_RFAX_FECH            DATETIME NULL,
SGD_RFAX_FECHRADI        DATETIME NULL,
RADI_NUME_RADI           BIGINT NULL,
SGD_RFAX_OBSERVA         VARCHAR(500) NULL
);
CREATE INDEX IDX_RFAX_CODIGO ON SGD_RFAX_RESERVAFAX (SGD_RFAX_CODIGO);
CREATE INDEX IDX_RFAX_FAX ON SGD_RFAX_RESERVAFAX (SGD_RFAX_FAX);
CREATE INDEX IDX_RFAX_FECH ON SGD_RFAX_RESERVAFAX (SGD_RFAX_FECH);
CREATE INDEX IDX_RFAX_RADI_NUME_RADI ON SGD_RFAX_RESERVAFAX (RADI_NUME_RADI);
CREATE TABLE SGD_SAN_SANCIONADOS (
SGD_SAN_REF              VARCHAR(20) NOT NULL,
SGD_SAN_DECISION         VARCHAR(60) NULL,
SGD_SAN_CARGO            VARCHAR(50) NULL,
SGD_SAN_EXPEDIENTE       VARCHAR(20) NULL,
SGD_SAN_TIPO_SANCION     VARCHAR(50) NULL,
SGD_SAN_PLAZO            VARCHAR(100) NULL,
SGD_SAN_VALOR            NUMERIC NULL,
SGD_SAN_RADICACION       VARCHAR(15) NULL,
SGD_SAN_FECHA_RADICADO   DATETIME NULL,
SGD_SAN_VALORLETRAS      VARCHAR(1000) NULL,
SGD_SAN_NOMBREEMPRESA    VARCHAR(160) NULL,
SGD_SAN_MOTIVOS          VARCHAR(160) NULL,
SGD_SAN_SECTORES         VARCHAR(160) NULL,
SGD_SAN_PADRE            VARCHAR(15) NULL,
SGD_SAN_FECHA_PADRE      DATETIME NULL,
SGD_SAN_NOTIFICADO       VARCHAR(100) NULL,
                 PRIMARY KEY (SGD_SAN_REF)
);
CREATE UNIQUE INDEX IDX_SGD_SAN_SANCIONADOS ON SGD_SAN_SANCIONADOS (SGD_SAN_REF);
CREATE TABLE SGD_SRD_SERIESRD (
SGD_SRD_CODIGO           SMALLINT NOT NULL,
SGD_SRD_DESCRIP          VARCHAR(50) NOT NULL,
SGD_SRD_FECHINI          DATETIME NOT NULL,
SGD_SRD_FECHFIN          DATETIME NOT NULL,
                 PRIMARY KEY (SGD_SRD_CODIGO)
);
CREATE UNIQUE INDEX IDX_SRD_SERIESRD ON SGD_SRD_SERIESRD (SGD_SRD_CODIGO);
CREATE UNIQUE INDEX IDX_SRD_DESCRIP ON SGD_SRD_SERIESRD (SGD_SRD_DESCRIP);
CREATE TABLE SGD_TME_TIPMEN (
SGD_TME_CODI             SMALLINT NOT NULL,
SGD_TME_DESC             VARCHAR(150) NULL,
                 PRIMARY KEY (SGD_TME_CODI)
);
CREATE UNIQUE INDEX IDX_TME_TIPMEN ON SGD_TME_TIPMEN (SGD_TME_CODI);
CREATE TABLE SGD_TRAD_TIPORAD (
SGD_TRAD_CODIGO          TINYINT NOT NULL,
SGD_TRAD_DESCR           VARCHAR(30) NULL,
SGD_TRAD_ICONO           VARCHAR(30) NULL,
SGD_TRAD_GENRADSAL       TINYINT NULL,
SGD_TRAD_DIASBLOQUEO     TINYINT DEFAULT 0,
                 PRIMARY KEY (SGD_TRAD_CODIGO)
);
CREATE UNIQUE INDEX IDX_TRAD_TIPORAD_CODIGO ON SGD_TRAD_TIPORAD (SGD_TRAD_CODIGO);
CREATE TABLE SGD_USH_USUHISTORICO (
SGD_USH_ADMCOD           BIGINT NOT NULL,
SGD_USH_ADMDEP           INT NOT NULL,
SGD_USH_ADMDOC           VARCHAR(14) NOT NULL,
SGD_USH_USUCOD           BIGINT NOT NULL,
SGD_USH_USUDEP           INT NOT NULL,
SGD_USH_USUDOC           VARCHAR(14) NOT NULL,
SGD_USH_MODCOD           INT NOT NULL,
SGD_USH_FECHEVENTO       DATETIME NOT NULL,
SGD_USH_USULOGIN         VARCHAR(20) NOT NULL
);
CREATE TABLE SGD_USM_USUMODIFICA (
SGD_USM_MODCOD           INT NOT NULL,
SGD_USM_MODDESCR         VARCHAR(60) NOT NULL
);
CREATE UNIQUE INDEX IDX_USM_MODCOD ON SGD_USM_USUMODIFICA (SGD_USM_MODCOD);
CREATE TABLE TIPO_DOC_IDENTIFICACION (
TDID_CODI                TINYINT NOT NULL,
TDID_DESC                VARCHAR(100) NOT NULL,
                 PRIMARY KEY (TDID_CODI)
);
CREATE UNIQUE INDEX IDX_TIPO_DOC_IDENTIFICACION ON TIPO_DOC_IDENTIFICACION (TDID_CODI);
CREATE TABLE TIPO_REMITENTE (
TRTE_CODI                TINYINT NOT NULL,
TRTE_DESC                VARCHAR(100) NOT NULL,
                 PRIMARY KEY (TRTE_CODI)
);
CREATE UNIQUE INDEX IDX_TIPO_REMITENTE ON TIPO_REMITENTE (TRTE_CODI);
CREATE TABLE SGD_ACTADD_ACTUALIADICIONAL (
SGD_ACTADD_CODI          SMALLINT NOT NULL,
SGD_APLI_CODI            SMALLINT NULL,
SGD_INSTORF_CODI         SMALLINT NULL,
SGD_ACTADD_QUERY         VARCHAR(500) NULL,
SGD_ACTADD_DESC          VARCHAR(150) NULL,
                 PRIMARY KEY (SGD_ACTADD_CODI)
, FOREIGN KEY (SGD_APLI_CODI) REFERENCES SGD_APLI_APLINTEGRA (SGD_APLI_CODI)
									   , FOREIGN KEY (SGD_INSTORF_CODI) REFERENCES SGD_INSTORF_INSTANCIASORFEO (SGD_INSTORF_CODI)
);
CREATE UNIQUE INDEX IDX_ACTADD_CODI ON SGD_ACTADD_ACTUALIADICIONAL (SGD_ACTADD_CODI);
CREATE TABLE SGD_APLFAD_PLICFUNADI (
SGD_APLFAD_CODI          SMALLINT NOT NULL,
SGD_APLI_CODI            SMALLINT NULL,
SGD_APLFAD_MENU          VARCHAR(150) NOT NULL,
SGD_APLFAD_LK1           VARCHAR(150) NOT NULL,
SGD_APLFAD_DESC          VARCHAR(150) NOT NULL,
                 PRIMARY KEY (SGD_APLFAD_CODI)
, FOREIGN KEY (SGD_APLI_CODI) REFERENCES SGD_APLI_APLINTEGRA (SGD_APLI_CODI)
);
CREATE UNIQUE INDEX SYS_C005036 ON SGD_APLFAD_PLICFUNADI (SGD_APLFAD_CODI);
CREATE TABLE SGD_APLMEN_APLIMENS (
SGD_APLMEN_CODI          SMALLINT NOT NULL,
SGD_APLI_CODI            SMALLINT NULL,
SGD_APLMEN_REF           VARCHAR(20) NULL,
SGD_APLMEN_HACIAORFEO    SMALLINT NULL,
SGD_APLMEN_DESDEORFEO    SMALLINT NULL,
                 PRIMARY KEY (SGD_APLMEN_CODI)
, FOREIGN KEY (SGD_APLI_CODI) REFERENCES SGD_APLI_APLINTEGRA (SGD_APLI_CODI)
);
CREATE UNIQUE INDEX SYS_C005038 ON SGD_APLMEN_APLIMENS (SGD_APLMEN_CODI);
CREATE TABLE SGD_APLUS_PLICUSUA (
SGD_APLUS_CODI           SMALLINT NOT NULL,
SGD_APLI_CODI            SMALLINT NULL,
USUA_DOC                 VARCHAR(14) NULL,
SGD_TRAD_CODIGO          TINYINT NULL,
SGD_APLUS_PRIORIDAD      TINYINT NULL,
                 PRIMARY KEY (SGD_APLUS_CODI)
, FOREIGN KEY (SGD_APLI_CODI) REFERENCES SGD_APLI_APLINTEGRA (SGD_APLI_CODI)
);
CREATE UNIQUE INDEX IDX_SGD_APLUS_PLICUSUA ON SGD_APLUS_PLICUSUA (SGD_APLUS_CODI);
CREATE TABLE SGD_DCAU_CAUSAL (
SGD_DCAU_CODIGO          SMALLINT NOT NULL,
SGD_CAU_CODIGO           SMALLINT NULL,
SGD_DCAU_DESCRIP         VARCHAR(150) NULL,
                 PRIMARY KEY (SGD_DCAU_CODIGO)
, FOREIGN KEY (SGD_CAU_CODIGO) REFERENCES SGD_CAU_CAUSAL (SGD_CAU_CODIGO)
);
CREATE INDEX IDX_SGD_DCAU_CAUSAL ON SGD_DCAU_CAUSAL (SGD_DCAU_CODIGO);
CREATE TABLE SGD_DDCA_DDSGRGDO (
SGD_DDCA_CODIGO          SMALLINT NOT NULL,
SGD_DCAU_CODIGO          SMALLINT NULL,
PAR_SERV_SECUE           INT NULL,
SGD_DDCA_DESCRIP         VARCHAR(150) NULL,
                 PRIMARY KEY (SGD_DDCA_CODIGO)
, FOREIGN KEY (PAR_SERV_SECUE) REFERENCES PAR_SERV_SERVICIOS (PAR_SERV_SECUE)
									   , FOREIGN KEY (SGD_DCAU_CODIGO) REFERENCES SGD_DCAU_CAUSAL (SGD_DCAU_CODIGO)
);
CREATE TABLE SGD_DEF_CONTACTOS (
CTT_ID                   BIGINT NOT NULL,
CTT_NOMBRE               VARCHAR(60) NOT NULL,
CTT_CARGO                VARCHAR(60) NOT NULL,
CTT_TELEFONO             VARCHAR(25) NULL,
CTT_ID_TIPO              SMALLINT NOT NULL,
CTT_ID_EMPRESA           BIGINT NOT NULL
);
CREATE TABLE SGD_DEVE_DEV_ENVIO (
SGD_DEVE_CODIGO          TINYINT NOT NULL,
SGD_DEVE_DESC            VARCHAR(150) NOT NULL,
                 PRIMARY KEY (SGD_DEVE_CODIGO)
);
CREATE INDEX IDX_SGD_DEVE ON SGD_DEVE_DEV_ENVIO (SGD_DEVE_CODIGO);
CREATE TABLE SGD_ESTINST_ESTADOINSTANCIA (
SGD_ESTINST_CODI         SMALLINT NOT NULL,
SGD_APLI_CODI            SMALLINT NULL,
SGD_INSTORF_CODI         SMALLINT NULL,
SGD_ESTINST_VALOR        SMALLINT NULL,
SGD_ESTINST_HABILITA     TINYINT NULL,
SGD_ESTINST_MENSAJE      VARCHAR(100) NULL,
                 PRIMARY KEY (SGD_ESTINST_CODI)
, FOREIGN KEY (SGD_APLI_CODI) REFERENCES SGD_APLI_APLINTEGRA (SGD_APLI_CODI)
									   , FOREIGN KEY (SGD_INSTORF_CODI) REFERENCES SGD_INSTORF_INSTANCIASORFEO (SGD_INSTORF_CODI)
);
CREATE UNIQUE INDEX SYS_C005088 ON SGD_ESTINST_ESTADOINSTANCIA (SGD_ESTINST_CODI);
CREATE TABLE SGD_PNUFE_PROCNUMFE (
SGD_PNUFE_CODI           SMALLINT NOT NULL,
SGD_TPR_CODIGO           SMALLINT NULL,
SGD_PNUFE_DESCRIP        VARCHAR(150) NULL,
SGD_PNUFE_SERIE          VARCHAR(50) NULL,
                 PRIMARY KEY (SGD_PNUFE_CODI)
);
CREATE UNIQUE INDEX IDX_PNUFE_PROCNUMFE ON SGD_PNUFE_PROCNUMFE (SGD_PNUFE_CODI);
CREATE TABLE SGD_PRD_PRCDMENTOS (
SGD_PRD_CODIGO           SMALLINT NOT NULL,
SGD_PRD_DESCRIP          VARCHAR(200) NULL,
SGD_PRD_FECH_INI         DATETIME NULL,
SGD_PRD_FECH_FIN         DATETIME NULL,
                 PRIMARY KEY (SGD_PRD_CODIGO)
);
CREATE UNIQUE INDEX IDX_PRD_PRCDMENTOS ON SGD_PRD_PRCDMENTOS (SGD_PRD_CODIGO);
CREATE TABLE SGD_SBRD_SUBSERIERD (
SGD_SRD_CODIGO           SMALLINT NOT NULL,
SGD_SBRD_CODIGO          SMALLINT NOT NULL,
SGD_SBRD_DESCRIP         VARCHAR(200) NOT NULL,
SGD_SBRD_FECHINI         DATETIME NOT NULL,
SGD_SBRD_FECHFIN         DATETIME NOT NULL,
SGD_SBRD_TIEMAG          SMALLINT NULL,
SGD_SBRD_TIEMAC          SMALLINT NULL,
SGD_SBRD_DISPFIN         VARCHAR(50) NULL,
SGD_SBRD_SOPORTE         VARCHAR(50) NULL,
SGD_SBRD_PROCEDI         VARCHAR(200) NULL,
                 PRIMARY KEY (SGD_SRD_CODIGO, SGD_SBRD_CODIGO)
, FOREIGN KEY (SGD_SRD_CODIGO) REFERENCES SGD_SRD_SERIESRD (SGD_SRD_CODIGO)
);
CREATE UNIQUE INDEX IDX_SBRD_SUBSERIERD ON SGD_SBRD_SUBSERIERD (SGD_SRD_CODIGO, SGD_SBRD_CODIGO);
CREATE TABLE SGD_TDEC_TIPODECISION (
SGD_APLI_CODI            SMALLINT NOT NULL,
SGD_TDEC_CODIGO          SMALLINT NOT NULL,
SGD_TDEC_DESCRIP         VARCHAR(150) NULL,
SGD_TDEC_SANCIONAR       TINYINT NULL,
SGD_TDEC_FIRMEZA         TINYINT NULL,
SGD_TDEC_VERSANCION      TINYINT NULL,
SGD_TDEC_SHOWMENU        TINYINT NULL,
SGD_TDEC_UPDNOTIF        TINYINT NULL,
                 PRIMARY KEY (SGD_TDEC_CODIGO)
, FOREIGN KEY (SGD_APLI_CODI) REFERENCES SGD_APLI_APLINTEGRA (SGD_APLI_CODI)
);
CREATE UNIQUE INDEX IDX_TDEC_TIPODECISION ON SGD_TDEC_TIPODECISION (SGD_TDEC_CODIGO);
CREATE TABLE SGD_TID_TIPDECISION (
SGD_TID_CODI             SMALLINT NOT NULL,
SGD_TID_DESC             VARCHAR(150) NULL,
SGD_TPR_CODIGO           SMALLINT NULL,
SGD_PEXP_CODIGO          INT NULL,
SGD_TPR_CODIGOP          TINYINT NULL,
                 PRIMARY KEY (SGD_TID_CODI)
);
CREATE UNIQUE INDEX IDX_TID_TIPDECISION ON SGD_TID_TIPDECISION (SGD_TID_CODI);
CREATE TABLE SGD_TPR_TPDCUMENTO (
SGD_TPR_CODIGO           SMALLINT NOT NULL,
SGD_TPR_DESCRIP          VARCHAR(150) NULL,
SGD_TPR_TERMINO          SMALLINT NULL,
SGD_TPR_TPUSO            TINYINT NULL,
SGD_TPR_NUMERA           VARCHAR(1) NULL,
SGD_TPR_RADICA           VARCHAR(1) NULL,
SGD_TPR_TP1              TINYINT DEFAULT 0,
SGD_TPR_TP2              TINYINT DEFAULT 0,
SGD_TPR_ESTADO           TINYINT NULL,
SGD_TERMINO_REAL         SMALLINT NULL,
                 PRIMARY KEY (SGD_TPR_CODIGO)
);
CREATE UNIQUE INDEX IDX_TPR_TPDCUMENTO ON SGD_TPR_TPDCUMENTO (SGD_TPR_CODIGO);
CREATE INDEX IND_TPR_TPDOCDESCRP ON SGD_TPR_TPDCUMENTO (SGD_TPR_DESCRIP);
CREATE TABLE SGD_APER_ADMINPERFILES (
SGD_APER_CODIGO          TINYINT NOT NULL,
SGD_APER_DESCRIPCION     VARCHAR(20) NULL,
                 PRIMARY KEY (SGD_APER_CODIGO)
);
CREATE UNIQUE INDEX IDX_APER_ADMINPERFILES ON SGD_APER_ADMINPERFILES (SGD_APER_CODIGO);
CREATE TABLE UBICACION_FISICA (
UBIC_DEPE_RADI           INT NOT NULL,
UBIC_DEPE_ARCH           INT NULL,
UBIC_INV_PISO            VARCHAR(2) NOT NULL,
UBIC_INV_PISO_DESC       VARCHAR(40) NULL,
UBIC_INV_ITEMSO          VARCHAR(40) NULL,
UBIC_INV_ITEMSN          VARCHAR(40) NULL,
UBIC_INV_ARCHIVADOR      VARCHAR(4) NULL
);
CREATE INDEX IDX_UBICACION_FISICA ON UBICACION_FISICA (UBIC_INV_PISO);
CREATE TABLE SGD_TIDM_TIDOCMASIVA (
SGD_TIDM_CODI            SMALLINT NOT NULL,
SGD_TIDM_DESC            VARCHAR(150) NULL,
                 PRIMARY KEY (SGD_TIDM_CODI)
);
CREATE UNIQUE INDEX IDX_TDM_TIDOMASIVA ON SGD_TIDM_TIDOCMASIVA (SGD_TIDM_CODI);
CREATE TABLE SGD_COB_CAMPOBLIGA (
SGD_COB_CODI             SMALLINT NOT NULL,
SGD_COB_DESC             VARCHAR(150) NULL,
SGD_COB_LABEL            VARCHAR(50) NULL,
SGD_TIDM_CODI            SMALLINT NULL,
                 PRIMARY KEY (SGD_COB_CODI)
, FOREIGN KEY (SGD_TIDM_CODI) REFERENCES SGD_TIDM_TIDOCMASIVA (SGD_TIDM_CODI)
);
CREATE INDEX IDX_SGD_COB_CAMPOBLIGA ON SGD_COB_CAMPOBLIGA (SGD_COB_CODI);
CREATE TABLE SGD_ARGUP_ARGUDOCTOP (
SGD_ARGUP_CODI           SMALLINT NOT NULL,
SGD_ARGUP_DESC           VARCHAR(50) NULL,
SGD_TPR_CODIGO           SMALLINT NULL,
                 PRIMARY KEY (SGD_ARGUP_CODI)
);
CREATE UNIQUE INDEX IDX_SGD_ARGUP_ARGUDOCTOP ON SGD_ARGUP_ARGUDOCTOP (SGD_ARGUP_CODI);
CREATE TABLE SGD_SED_SEDE (
SGD_SED_CODI             SMALLINT NOT NULL,
SGD_SED_DESC             VARCHAR(50) NULL,
SGD_TPR_CODIGO           SMALLINT NULL,
                 PRIMARY KEY (SGD_SED_CODI)
);
CREATE UNIQUE INDEX SYS_C005196 ON SGD_SED_SEDE (SGD_SED_CODI);
CREATE TABLE SGD_ENT_ENTIDADES (
SGD_ENT_NIT              VARCHAR(13) NOT NULL,
SGD_ENT_CODSUC           VARCHAR(4) NOT NULL,
SGD_ENT_PIAS             INT NULL,
DPTO_CODI                SMALLINT NULL,
MUNI_CODI                SMALLINT NULL,
SGD_ENT_DESCRIP          VARCHAR(80) NULL,
SGD_ENT_DIRECCION        VARCHAR(50) NULL,
SGD_ENT_TELEFONO         VARCHAR(50) NULL,
                 PRIMARY KEY (SGD_ENT_NIT, SGD_ENT_CODSUC)
);
CREATE TABLE SGD_FENV_FRMENVIO (
SGD_FENV_CODIGO          INT NOT NULL,
SGD_FENV_DESCRIP         VARCHAR(40) NOT NULL,
SGD_FENV_PLANILLA        TINYINT DEFAULT 0 NOT NULL,
SGD_FENV_ESTADO          TINYINT DEFAULT 1 NOT NULL,
                 PRIMARY KEY (SGD_FENV_CODIGO)
);
CREATE UNIQUE INDEX IDX_SGD_FENV ON SGD_FENV_FRMENVIO (SGD_FENV_CODIGO);
CREATE TABLE SGD_SENUF_SECNUMFE (
SGD_SENUF_CODI           SMALLINT NOT NULL,
SGD_PNUFE_CODI           SMALLINT NULL,
DEPE_CODI                INT NULL,
SGD_SENUF_SEC            VARCHAR(50) NULL,
                 PRIMARY KEY (SGD_SENUF_CODI)
);
CREATE UNIQUE INDEX IDX_SENUF_CODI ON SGD_SENUF_SECNUMFE (SGD_SENUF_CODI);
CREATE TABLE SGD_FLD_FLUJODOC (
SGD_FLD_CODIGO           SMALLINT NULL,
SGD_FLD_DESC             VARCHAR(100) NULL,
SGD_TPR_CODIGO           SMALLINT NULL,
SGD_FLD_IMAGEN           VARCHAR(50) NULL,
SGD_FLD_GRUPOWEB         INT DEFAULT 0
);
CREATE TABLE SGD_RMR_RADMASIVRE (
SGD_RMR_GRUPO            BIGINT NOT NULL,
SGD_RMR_RADI             BIGINT NOT NULL,
                 PRIMARY KEY (SGD_RMR_GRUPO, SGD_RMR_RADI)
);
CREATE UNIQUE INDEX IDX_RMR_RADMASIVRE ON SGD_RMR_RADMASIVRE (SGD_RMR_GRUPO, SGD_RMR_RADI);
CREATE TABLE SGD_ARG_PLIEGO (
SGD_ARG_CODIGO           TINYINT NOT NULL,
SGD_ARG_DESC             VARCHAR(150) NOT NULL
);
CREATE TABLE SGD_PANU_PERANULADOS (
SGD_PANU_CODI            SMALLINT NOT NULL,
SGD_PANU_DESC            VARCHAR(200) NULL,
                 PRIMARY KEY (SGD_PANU_CODI)
);
CREATE UNIQUE INDEX IDX_PERANUALDOS ON SGD_PANU_PERANULADOS (SGD_PANU_CODI);
CREATE TABLE SGD_TRES_TPRESOLUCION (
SGD_TRES_CODIGO          TINYINT NOT NULL,
SGD_TRES_DESCRIP         VARCHAR(100) NOT NULL,
SGD_TPR_CODIGO           SMALLINT NULL,
                 PRIMARY KEY (SGD_TRES_CODIGO)
);
CREATE UNIQUE INDEX IDX_TRES_TPRESOLUCION ON SGD_TRES_TPRESOLUCION (SGD_TRES_CODIGO);
CREATE TABLE SGD_TIP3_TIPOTERCERO (
SGD_TIP3_CODIGO          TINYINT NOT NULL,
SGD_DIR_TIPO             SMALLINT NULL,
SGD_TIP3_NOMBRE          VARCHAR(15) NULL,
SGD_TIP3_DESC            VARCHAR(30) NULL,
SGD_TIP3_IMGPESTANA      VARCHAR(20) NULL,
SGD_TPR_TP1              TINYINT DEFAULT 0,
SGD_TPR_TP2              TINYINT DEFAULT 0,
                 PRIMARY KEY (SGD_TIP3_CODIGO)
);
CREATE TABLE SGD_TTR_TRANSACCION (
SGD_TTR_CODIGO           SMALLINT NOT NULL,
SGD_TTR_DESCRIP          VARCHAR(100) NOT NULL,
                 PRIMARY KEY (SGD_TTR_CODIGO)
);
CREATE UNIQUE INDEX IDX_TTR_TRANSACCION ON SGD_TTR_TRANSACCION (SGD_TTR_CODIGO);
CREATE TABLE SGD_MPES_MDDPESO (
SGD_MPES_CODIGO          INT NOT NULL,
SGD_MPES_DESCRIP         VARCHAR(10) NULL,
                 PRIMARY KEY (SGD_MPES_CODIGO)
);
CREATE UNIQUE INDEX IDX_MPES ON SGD_MPES_MDDPESO (SGD_MPES_CODIGO);
CREATE TABLE SGD_ENVE_ENVIOESPECIAL (
SGD_FENV_CODIGO          INT NULL,
SGD_ENVE_VALORL          VARCHAR(30) NULL,
SGD_ENVE_VALORN          VARCHAR(30) NULL,
SGD_ENVE_DESC            VARCHAR(30) NULL
, FOREIGN KEY (SGD_FENV_CODIGO) REFERENCES SGD_FENV_FRMENVIO (SGD_FENV_CODIGO)
);
CREATE TABLE SGD_CLTA_CLSTARIF (
SGD_FENV_CODIGO          INT NULL,
SGD_CLTA_CODSER          INT NULL,
SGD_TAR_CODIGO           INT NULL,
SGD_CLTA_DESCRIP         VARCHAR(100) NULL,
SGD_CLTA_PESDES          BIGINT NULL,
SGD_CLTA_PESHAST         BIGINT NULL
);
CREATE TABLE SGD_EANU_ESTANULACION (
SGD_EANU_DESC            VARCHAR(150) NULL,
SGD_EANU_CODI            INT NOT NULL,
                 PRIMARY KEY (SGD_EANU_CODI)
);
CREATE TABLE SGD_TAR_TARIFAS (
SGD_FENV_CODIGO          INT NULL,
SGD_TAR_CODSER           INT NULL,
SGD_TAR_CODIGO           INT NULL,
SGD_TAR_VALENV1          BIGINT NULL,
SGD_TAR_VALENV2          BIGINT NULL,
SGD_TAR_VALENV1G1        BIGINT NULL,
SGD_CLTA_CODSER          INT NULL,
SGD_TAR_VALENV2G2        BIGINT NULL,
SGD_CLTA_DESCRIP         VARCHAR(100) NULL
);
CREATE TABLE SGD_DEF_CONTINENTES (
ID_CONT                  TINYINT NOT NULL,
NOMBRE_CONT              VARCHAR(20) NOT NULL,
                 PRIMARY KEY (ID_CONT)
);
CREATE INDEX IDX_DEF_CONTINENTES ON SGD_DEF_CONTINENTES (ID_CONT);
CREATE TABLE SGD_DEF_PAISES (
ID_CONT                  TINYINT DEFAULT 1 NOT NULL,
ID_PAIS                  SMALLINT DEFAULT 170 NOT NULL,
NOMBRE_PAIS              VARCHAR(30) NOT NULL,
                 PRIMARY KEY (ID_CONT, ID_PAIS)
, FOREIGN KEY (ID_CONT) REFERENCES SGD_DEF_CONTINENTES (ID_CONT)
);
CREATE INDEX IDX_DEF_PAISES ON SGD_DEF_PAISES (ID_CONT);
CREATE TABLE DEPARTAMENTO (
ID_CONT                  TINYINT DEFAULT 1 NOT NULL,
ID_PAIS                  SMALLINT DEFAULT 170 NOT NULL,
DPTO_CODI                SMALLINT NOT NULL,
DPTO_NOMB                VARCHAR(70) NOT NULL,
                 PRIMARY KEY (ID_CONT, ID_PAIS, DPTO_CODI)
, FOREIGN KEY (ID_CONT,ID_PAIS) REFERENCES SGD_DEF_PAISES (ID_CONT,ID_PAIS)
);
CREATE TABLE MUNICIPIO (
ID_CONT                  TINYINT NOT NULL,
ID_PAIS                  SMALLINT NOT NULL,
DPTO_CODI                SMALLINT NOT NULL,
MUNI_CODI                SMALLINT NOT NULL,
MUNI_NOMB                VARCHAR(100) NOT NULL,
HOMOLOGA_MUNI            VARCHAR(10) NULL,
HOMOLOGA_IDMUNI          SMALLINT NULL,
ACTIVA                   TINYINT DEFAULT 1,
                 PRIMARY KEY (ID_CONT, ID_PAIS, DPTO_CODI, MUNI_CODI)
, FOREIGN KEY (ID_CONT,ID_PAIS,DPTO_CODI) REFERENCES DEPARTAMENTO (ID_CONT,ID_PAIS,DPTO_CODI)
);
CREATE UNIQUE INDEX IDX_MUNICIPIO ON MUNICIPIO (ID_CONT, ID_PAIS, DPTO_CODI, MUNI_CODI);
CREATE TABLE DEPENDENCIA (
DEPE_CODI                SMALLINT NOT NULL,
DEPE_NOMB                VARCHAR(70) NOT NULL,
DPTO_CODI                SMALLINT NULL,
DEPE_CODI_PADRE          SMALLINT NULL,
MUNI_CODI                SMALLINT NULL,
DEPE_CODI_TERRITORIAL    SMALLINT NULL,
DEP_SIGLA                VARCHAR(100) NULL,
DEP_CENTRAL              SMALLINT NULL,
DEP_DIRECCION            VARCHAR(100) NULL,
DEPE_NUM_INTERNA         SMALLINT NULL,
DEPE_NUM_RESOLUCION      SMALLINT NULL,
DEPE_RAD_TP1             SMALLINT NULL,
DEPE_RAD_TP2             SMALLINT NULL,
ID_CONT                  TINYINT DEFAULT 1,
ID_PAIS                  SMALLINT DEFAULT 170,
DEPE_ESTADO              TINYINT DEFAULT 1,
                 PRIMARY KEY (DEPE_CODI)
, FOREIGN KEY (ID_CONT,ID_PAIS,DPTO_CODI,MUNI_CODI) REFERENCES MUNICIPIO (ID_CONT,ID_PAIS,DPTO_CODI,MUNI_CODI)
									   , FOREIGN KEY (DEPE_CODI_PADRE) REFERENCES DEPENDENCIA (DEPE_CODI)
);
CREATE UNIQUE INDEX IDX_DEPE ON DEPENDENCIA (DEPE_CODI);
CREATE TABLE CARPETA_PER (
USUA_CODI                SMALLINT NOT NULL,
DEPE_CODI                SMALLINT NOT NULL,
NOMB_CARP                VARCHAR(10) NULL,
DESC_CARP                VARCHAR(30) NULL,
CODI_CARP                SMALLINT NOT NULL,
                 PRIMARY KEY (USUA_CODI, DEPE_CODI, CODI_CARP)
, FOREIGN KEY (DEPE_CODI) REFERENCES DEPENDENCIA (DEPE_CODI)
);
CREATE INDEX CARPETAS_PER1 ON CARPETA_PER (USUA_CODI, DEPE_CODI);
CREATE INDEX CARPETAS_PER ON CARPETA_PER (CODI_CARP);
CREATE TABLE DEPENDENCIA_VISIBILIDAD (
CODIGO_VISIBILIDAD       BIGINT NOT NULL,
DEPENDENCIA_VISIBLE      SMALLINT NOT NULL,
DEPENDENCIA_OBSERVA      SMALLINT NOT NULL,
                 PRIMARY KEY (CODIGO_VISIBILIDAD)
, FOREIGN KEY (DEPENDENCIA_VISIBLE) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (DEPENDENCIA_OBSERVA) REFERENCES DEPENDENCIA (DEPE_CODI)
);
CREATE UNIQUE INDEX IDX_DEPENDENCIA_VISIBILIDAD ON DEPENDENCIA_VISIBILIDAD (CODIGO_VISIBILIDAD);
CREATE TABLE USUARIO (
USUA_CODI                SMALLINT NOT NULL,
DEPE_CODI                SMALLINT NOT NULL,
USUA_LOGIN               VARCHAR(15) NOT NULL,
USUA_FECH_CREA           DATETIME NOT NULL,
USUA_PASW                VARCHAR(30) NOT NULL,
USUA_ESTA                VARCHAR(10) NOT NULL,
USUA_NOMB                VARCHAR(45) NULL,
PERM_RADI                CHAR(1) DEFAULT 0,
USUA_ADMIN               CHAR(1) DEFAULT 0,
USUA_NUEVO               CHAR(1) DEFAULT 0,
USUA_DOC                 VARCHAR(14) DEFAULT '0',
CODI_NIVEL               TINYINT DEFAULT 1,
USUA_SESION              VARCHAR(30) NULL,
USUA_FECH_SESION         DATETIME NULL,
USUA_EXT                 SMALLINT NULL,
USUA_NACIM               DATETIME NULL,
USUA_EMAIL               VARCHAR(50) NULL,
USUA_AT                  VARCHAR(15) NULL,
USUA_PISO                TINYINT NULL,
PERM_RADI_SAL            INT DEFAULT 0,
USUA_ADMIN_ARCHIVO       TINYINT DEFAULT 0,
USUA_MASIVA              TINYINT DEFAULT 0,
USUA_PERM_DEV            TINYINT DEFAULT 0,
USUA_PERM_NUMERA_RES     VARCHAR(1) NULL,
USUA_DOC_SUIP            VARCHAR(15) NULL,
USUA_PERM_NUMERADOC      TINYINT NULL,
SGD_PANU_CODI            SMALLINT NULL,
USUA_PRAD_TP1            TINYINT DEFAULT 0,
USUA_PRAD_TP2            TINYINT DEFAULT 0,
USUA_PERM_ENVIOS         TINYINT DEFAULT 0,
USUA_PERM_MODIFICA       TINYINT DEFAULT 0,
USUA_PERM_IMPRESION      TINYINT DEFAULT 0,
SGD_APER_CODIGO          TINYINT NULL,
USU_TELEFONO1            VARCHAR(14) NULL,
USUA_ENCUESTA            VARCHAR(1) NULL,
SGD_PERM_ESTADISTICA     TINYINT NULL,
USUA_PERM_SANCIONADOS    TINYINT NULL,
USUA_ADMIN_SISTEMA       TINYINT NULL,
USUA_PERM_TRD            TINYINT NULL,
USUA_PERM_FIRMA          TINYINT NULL,
USUA_PERM_PRESTAMO       TINYINT NULL,
USUARIO_PUBLICO          TINYINT NULL,
USUARIO_REASIGNAR        TINYINT NULL,
USUA_PERM_NOTIFICA       TINYINT NULL,
USUA_PERM_EXPEDIENTE     INT NULL,
USUA_LOGIN_EXTERNO       VARCHAR(15) NULL,
ID_PAIS                  SMALLINT DEFAULT 170,
ID_CONT                  TINYINT DEFAULT 1,
PERM_TIPIF_ANEXO         INT NULL,
PERM_VOBO                VARCHAR(1) DEFAULT '1',
PERM_ARCHI               CHAR(1) DEFAULT 1,
PERM_BORRAR_ANEXO        INT NULL,
USUA_AUTH_LDAP           INT NULL,
USUA_PERM_ADMINFLUJOS    TINYINT DEFAULT 0,
USUA_ADM_PLANTILLA       TINYINT DEFAULT 0,
USUA_PERM_INTERGAPPS     TINYINT DEFAULT 0,
                 PRIMARY KEY (USUA_LOGIN)
, FOREIGN KEY (DEPE_CODI) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (SGD_APER_CODIGO) REFERENCES SGD_APER_ADMINPERFILES (SGD_APER_CODIGO)
);
CREATE UNIQUE INDEX IDX_USUARIO ON USUARIO (USUA_CODI, DEPE_CODI);
CREATE UNIQUE INDEX IDX_USUA_LOGIN ON USUARIO (USUA_LOGIN);
CREATE INDEX IDX_USUA_DOC ON USUARIO (USUA_DOC);
CREATE TABLE SGD_ADMIN_DEPE_HISTORICO (
ADMIN_DEPE_HISTORICO_CODIGO BIGINT NOT NULL,
USUARIO_CODIGO_ADMINISTRADOR BIGINT NOT NULL,
DEPENDENCIA_CODIGO_ADMINISTRADOR SMALLINT NOT NULL,
USUARIO_DOCUMENTO_ADMINISTRADOR VARCHAR(14) NOT NULL,
DEPENDENCIA_MODIFICADA   SMALLINT NOT NULL,
ADMIN_OBSERVACION_CODIGO BIGINT NOT NULL,
ADMIN_FECHA_EVENTO       DATETIME NOT NULL,
                 PRIMARY KEY (ADMIN_DEPE_HISTORICO_CODIGO)
, FOREIGN KEY (DEPENDENCIA_MODIFICADA) REFERENCES DEPENDENCIA (DEPE_CODI)
);
CREATE TABLE SGD_ADMIN_USUA_HISTORICO (
ADMIN_HISTORICO_CODIGO   BIGINT NOT NULL,
USUARIO_CODIGO_ADMINISTRADOR BIGINT NOT NULL,
DEPENDENCIA_CODIGO_ADMINISTRADOR SMALLINT NOT NULL,
USUARIO_DOCUMENTO_ADMINISTRADOR VARCHAR(14) NOT NULL,
USUARIO_CODIGO_MODIFICADO BIGINT NOT NULL,
DEPENDENCIA_CODIGO_MODIFICADO SMALLINT NOT NULL,
USUARIO_DOCUMENTO_MODIFICADO VARCHAR(14) NOT NULL,
ADMIN_OBSERVACION_CODIGO BIGINT NOT NULL,
ADMIN_FECHA_EVENTO       DATETIME NOT NULL,
                 PRIMARY KEY (ADMIN_HISTORICO_CODIGO)
, FOREIGN KEY (DEPENDENCIA_CODIGO_ADMINISTRADOR) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (DEPENDENCIA_CODIGO_MODIFICADO) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (ADMIN_OBSERVACION_CODIGO) REFERENCES SGD_ADMIN_OBSERVACION (CODIGO_OBSERVACION)
);
CREATE TABLE SGD_CARP_DESCRIPCION (
SGD_CARP_DEPECODI        SMALLINT NOT NULL,
SGD_CARP_TIPORAD         TINYINT NOT NULL,
SGD_CARP_DESCR           VARCHAR(40) NULL,
                 PRIMARY KEY (SGD_CARP_DEPECODI, SGD_CARP_TIPORAD)
, FOREIGN KEY (SGD_CARP_DEPECODI) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (SGD_CARP_TIPORAD) REFERENCES SGD_TRAD_TIPORAD (SGD_TRAD_CODIGO)
);
CREATE UNIQUE INDEX IDX_CARP_DESCRIPCION ON SGD_CARP_DESCRIPCION (SGD_CARP_DEPECODI, SGD_CARP_TIPORAD);
CREATE TABLE SGD_DNUFE_DOCNUFE (
SGD_DNUFE_CODI           SMALLINT NOT NULL,
SGD_PNUFE_CODI           SMALLINT NULL,
SGD_TPR_CODIGO           SMALLINT NULL,
SGD_DNUFE_LABEL          VARCHAR(150) NULL,
TRTE_CODI                TINYINT NULL,
SGD_DNUFE_MAIN           VARCHAR(1) NULL,
SGD_DNUFE_PATH           VARCHAR(150) NULL,
SGD_DNUFE_GERARQ         VARCHAR(10) NULL,
ANEX_TIPO_CODI           SMALLINT NULL,
                 PRIMARY KEY (SGD_DNUFE_CODI)
, FOREIGN KEY (ANEX_TIPO_CODI) REFERENCES ANEXOS_TIPO (ANEX_TIPO_CODI)
									   , FOREIGN KEY (SGD_PNUFE_CODI) REFERENCES SGD_PNUFE_PROCNUMFE (SGD_PNUFE_CODI)
									   , FOREIGN KEY (SGD_TPR_CODIGO) REFERENCES SGD_TPR_TPDCUMENTO (SGD_TPR_CODIGO)
									   , FOREIGN KEY (TRTE_CODI) REFERENCES TIPO_REMITENTE (TRTE_CODI)
);
CREATE UNIQUE INDEX IDX_DNUFE_DOCNUFE ON SGD_DNUFE_DOCNUFE (SGD_DNUFE_CODI);
CREATE TABLE SGD_CIU_CIUDADANO (
TDID_CODI                TINYINT NULL,
SGD_CIU_CODIGO           INT NOT NULL,
SGD_CIU_NOMBRE           VARCHAR(150) NULL,
SGD_CIU_DIRECCION        VARCHAR(150) NULL,
SGD_CIU_APELL1           VARCHAR(50) NULL,
SGD_CIU_APELL2           VARCHAR(50) NULL,
SGD_CIU_TELEFONO         VARCHAR(50) NULL,
SGD_CIU_EMAIL            VARCHAR(50) NULL,
MUNI_CODI                SMALLINT NULL,
DPTO_CODI                SMALLINT NULL,
SGD_CIU_CEDULA           VARCHAR(13) NULL,
ID_CONT                  TINYINT DEFAULT 1,
ID_PAIS                  SMALLINT DEFAULT 170,
                 PRIMARY KEY (SGD_CIU_CODIGO)
, FOREIGN KEY (ID_CONT,ID_PAIS,DPTO_CODI,MUNI_CODI) REFERENCES MUNICIPIO (ID_CONT,ID_PAIS,DPTO_CODI,MUNI_CODI)
									   , FOREIGN KEY (TDID_CODI) REFERENCES TIPO_DOC_IDENTIFICACION (TDID_CODI)
);
CREATE UNIQUE INDEX IDX_SGD_CIU_CIUDADANO ON SGD_CIU_CIUDADANO (SGD_CIU_CODIGO);
CREATE INDEX SGD_BUSCAR_NOMBRE ON SGD_CIU_CIUDADANO (SGD_CIU_NOMBRE, SGD_CIU_APELL1, SGD_CIU_APELL2);
CREATE INDEX SGD_CIU_INTE ON SGD_CIU_CIUDADANO (MUNI_CODI, DPTO_CODI, ID_CONT);
CREATE TABLE SGD_MAT_MATRIZ (
SGD_MAT_CODIGO           SMALLINT NOT NULL,
DEPE_CODI                SMALLINT NULL,
SGD_FUN_CODIGO           SMALLINT NULL,
SGD_PRC_CODIGO           SMALLINT NULL,
SGD_PRD_CODIGO           SMALLINT NULL,
SGD_MAT_FECH_INI         DATETIME NULL,
SGD_MAT_FECH_FIN         DATETIME NULL,
SGD_MAT_PESO_PRD         NUMERIC NULL,
                 PRIMARY KEY (SGD_MAT_CODIGO)
, FOREIGN KEY (DEPE_CODI) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (SGD_FUN_CODIGO) REFERENCES SGD_FUN_FUNCIONES (SGD_FUN_CODIGO)
									   , FOREIGN KEY (SGD_PRC_CODIGO) REFERENCES SGD_PRC_PROCESO (SGD_PRC_CODIGO)
									   , FOREIGN KEY (SGD_PRD_CODIGO) REFERENCES SGD_PRD_PRCDMENTOS (SGD_PRD_CODIGO)
);
CREATE UNIQUE INDEX IDX_MAT_MATRIZ ON SGD_MAT_MATRIZ (SGD_MAT_CODIGO);
CREATE UNIQUE INDEX IDX_MAT ON SGD_MAT_MATRIZ (DEPE_CODI, SGD_FUN_CODIGO, SGD_PRC_CODIGO, SGD_PRD_CODIGO);
CREATE TABLE SGD_MRD_MATRIRD (
SGD_MRD_CODIGO           SMALLINT NOT NULL,
DEPE_CODI                SMALLINT NOT NULL,
SGD_SRD_CODIGO           SMALLINT NOT NULL,
SGD_SBRD_CODIGO          SMALLINT NOT NULL,
SGD_TPR_CODIGO           SMALLINT NOT NULL,
SOPORTE                  VARCHAR(10) NULL,
SGD_MRD_FECHINI          DATETIME NULL,
SGD_MRD_FECHFIN          DATETIME NULL,
SGD_MRD_ESTA             VARCHAR(10) NULL,
                 PRIMARY KEY (SGD_MRD_CODIGO)
, FOREIGN KEY (DEPE_CODI) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (SGD_SRD_CODIGO) REFERENCES SGD_SRD_SERIESRD (SGD_SRD_CODIGO)
									   , FOREIGN KEY (SGD_SRD_CODIGO, SGD_SBRD_CODIGO) REFERENCES SGD_SBRD_SUBSERIERD (SGD_SRD_CODIGO, SGD_SBRD_CODIGO)
									   , FOREIGN KEY (SGD_TPR_CODIGO) REFERENCES SGD_TPR_TPDCUMENTO (SGD_TPR_CODIGO)
);
CREATE UNIQUE INDEX IDX_MRD_CODIGO ON SGD_MRD_MATRIRD (SGD_MRD_CODIGO);
CREATE UNIQUE INDEX IDX_MRD_MATRIRD ON SGD_MRD_MATRIRD (DEPE_CODI, SGD_SRD_CODIGO, SGD_SBRD_CODIGO, SGD_TPR_CODIGO);
CREATE TABLE SGD_MSG_MENSAJE (
SGD_MSG_CODI             BIGINT NOT NULL,
SGD_TME_CODI             SMALLINT NOT NULL,
SGD_MSG_DESC             VARCHAR(150) NULL,
SGD_MSG_FECHDESP         DATETIME NOT NULL,
SGD_MSG_URL              VARCHAR(150) NOT NULL,
SGD_MSG_VECES            SMALLINT NOT NULL,
SGD_MSG_ANCHO            INT NOT NULL,
SGD_MSG_LARGO            INT NOT NULL,
                 PRIMARY KEY (SGD_MSG_CODI)
, FOREIGN KEY (SGD_TME_CODI) REFERENCES SGD_TME_TIPMEN (SGD_TME_CODI)
);
CREATE UNIQUE INDEX IDX_MSG_MENSAJE ON SGD_MSG_MENSAJE (SGD_MSG_CODI);
CREATE TABLE SGD_MSDEP_MSGDEP (
SGD_MSDEP_CODI           BIGINT NOT NULL,
DEPE_CODI                SMALLINT NOT NULL,
SGD_MSG_CODI             BIGINT NOT NULL,
                 PRIMARY KEY (SGD_MSDEP_CODI)
, FOREIGN KEY (DEPE_CODI) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (SGD_MSG_CODI) REFERENCES SGD_MSG_MENSAJE (SGD_MSG_CODI)
);
CREATE UNIQUE INDEX IDX_MSDEP_MSGDEP ON SGD_MSDEP_MSGDEP (SGD_MSDEP_CODI);
CREATE TABLE SGD_MTD_MATRIZ_DOC (
SGD_MTD_CODIGO           SMALLINT NOT NULL,
SGD_MAT_CODIGO           SMALLINT NULL,
SGD_TPR_CODIGO           SMALLINT NULL,
                 PRIMARY KEY (SGD_MTD_CODIGO)
, FOREIGN KEY (SGD_MAT_CODIGO) REFERENCES SGD_MAT_MATRIZ (SGD_MAT_CODIGO)
									   , FOREIGN KEY (SGD_TPR_CODIGO) REFERENCES SGD_TPR_TPDCUMENTO (SGD_TPR_CODIGO)
);
CREATE UNIQUE INDEX IDX_MTD_MATRIZ_DOC ON SGD_MTD_MATRIZ_DOC (SGD_MTD_CODIGO);
CREATE TABLE SGD_PAREXP_PARAMEXPEDIENTE (
SGD_PAREXP_CODIGO        SMALLINT NOT NULL,
DEPE_CODI                SMALLINT NOT NULL,
SGD_PAREXP_TABLA         VARCHAR(30) NOT NULL,
SGD_PAREXP_ETIQUETA      VARCHAR(15) NOT NULL,
SGD_PAREXP_ORDEN         TINYINT NULL,
                 PRIMARY KEY (SGD_PAREXP_CODIGO)
, FOREIGN KEY (DEPE_CODI) REFERENCES DEPENDENCIA (DEPE_CODI)
);
CREATE UNIQUE INDEX IDX_PAREXP_PARAMEXPEDIENTE ON SGD_PAREXP_PARAMEXPEDIENTE (SGD_PAREXP_CODIGO);
CREATE TABLE SGD_PEXP_PROCEXPEDIENTES (
SGD_PEXP_CODIGO          INT NOT NULL,
SGD_PEXP_DESCRIP         VARCHAR(100) NULL,
SGD_PEXP_TERMINOS        INT DEFAULT 0,
SGD_SRD_CODIGO           SMALLINT NULL,
SGD_SBRD_CODIGO          SMALLINT NULL,
SGD_PEXP_AUTOMATICO      TINYINT DEFAULT 1,
SGD_PEXP_TIENEFLUJO      TINYINT DEFAULT 0 NOT NULL,
                 PRIMARY KEY (SGD_PEXP_CODIGO)
, FOREIGN KEY (SGD_SRD_CODIGO,SGD_SBRD_CODIGO) REFERENCES SGD_SBRD_SUBSERIERD (SGD_SRD_CODIGO,SGD_SBRD_CODIGO)
);
CREATE UNIQUE INDEX IDX_PEXP_PROCEXPEDIENTES ON SGD_PEXP_PROCEXPEDIENTES (SGD_PEXP_CODIGO);
CREATE TABLE SGD_RDF_RETDOCF (
SGD_MRD_CODIGO           SMALLINT NOT NULL,
RADI_NUME_RADI           BIGINT NOT NULL,
DEPE_CODI                SMALLINT NOT NULL,
USUA_CODI                BIGINT NOT NULL,
USUA_DOC                 VARCHAR(14) NOT NULL,
SGD_RDF_FECH             DATETIME NOT NULL
, FOREIGN KEY (DEPE_CODI) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (SGD_MRD_CODIGO) REFERENCES SGD_MRD_MATRIRD (SGD_MRD_CODIGO)
);
CREATE UNIQUE INDEX IDX_RDF_RETDOCF ON SGD_RDF_RETDOCF (SGD_MRD_CODIGO, RADI_NUME_RADI, DEPE_CODI);
CREATE TABLE SGD_SEXP_SECEXPEDIENTES (
SGD_EXP_NUMERO           VARCHAR(18) NOT NULL,
SGD_SRD_CODIGO           INT NULL,
SGD_SBRD_CODIGO          INT NULL,
SGD_SEXP_SECUENCIA       INT NULL,
DEPE_CODI                SMALLINT NULL,
USUA_DOC                 VARCHAR(15) NULL,
SGD_SEXP_FECH            DATETIME NULL,
SGD_FEXP_CODIGO          INT NULL,
SGD_SEXP_ANO             SMALLINT NULL,
USUA_DOC_RESPONSABLE     VARCHAR(18) NULL,
SGD_SEXP_PAREXP1         VARCHAR(250) NULL,
SGD_SEXP_PAREXP2         VARCHAR(160) NULL,
SGD_SEXP_PAREXP3         VARCHAR(160) NULL,
SGD_SEXP_PAREXP4         VARCHAR(160) NULL,
SGD_SEXP_PAREXP5         VARCHAR(160) NULL,
SGD_PEXP_CODIGO          INT NULL,
SGD_EXP_FECH_ARCH        DATETIME NULL,
SGD_FLD_CODIGO           SMALLINT NULL,
SGD_EXP_FECHFLUJOANT     DATETIME NULL,
SGD_MRD_CODIGO           SMALLINT NULL,
SGD_EXP_SUBEXPEDIENTE    BIGINT NULL,
                 PRIMARY KEY (SGD_EXP_NUMERO)
, FOREIGN KEY (SGD_PEXP_CODIGO) REFERENCES SGD_PEXP_PROCEXPEDIENTES (SGD_PEXP_CODIGO)
);
CREATE UNIQUE INDEX IDX_SEXP_SECEXPEDIENTES ON SGD_SEXP_SECEXPEDIENTES (SGD_EXP_NUMERO);
CREATE INDEX SGD_SEXP_SRD ON SGD_SEXP_SECEXPEDIENTES (SGD_SRD_CODIGO);
CREATE INDEX SGD_SEXP_SBRD ON SGD_SEXP_SECEXPEDIENTES (SGD_SBRD_CODIGO);
CREATE INDEX SGD_SEXP_PROC ON SGD_SEXP_SECEXPEDIENTES (SGD_FEXP_CODIGO);
CREATE TABLE SGD_CAMEXP_CAMPOEXPEDIENTE (
SGD_CAMEXP_CODIGO        SMALLINT NOT NULL,
SGD_CAMEXP_CAMPO         VARCHAR(30) NOT NULL,
SGD_PAREXP_CODIGO        SMALLINT NOT NULL,
SGD_CAMEXP_FK            INT DEFAULT 0,
SGD_CAMEXP_TABLAFK       VARCHAR(30) NULL,
SGD_CAMEXP_CAMPOFK       VARCHAR(30) NULL,
SGD_CAMEXP_CAMPOVALOR    VARCHAR(30) NULL,
SGD_CAMPEXP_ORDEN        TINYINT NULL,
                 PRIMARY KEY (SGD_CAMEXP_CODIGO)
, FOREIGN KEY (SGD_PAREXP_CODIGO) REFERENCES SGD_PAREXP_PARAMEXPEDIENTE (SGD_PAREXP_CODIGO)
);
CREATE UNIQUE INDEX IDX_SGD_CAMEXP_CAMPOEXPEDIENTE ON SGD_CAMEXP_CAMPOEXPEDIENTE (SGD_CAMEXP_CODIGO);
CREATE TABLE SGD_FEXP_FLUJOEXPEDIENTES (
SGD_FEXP_CODIGO          INT NOT NULL,
SGD_PEXP_CODIGO          INT NULL,
SGD_FEXP_ORDEN           SMALLINT NULL,
SGD_FEXP_TERMINOS        SMALLINT NULL,
SGD_FEXP_IMAGEN          VARCHAR(50) NULL,
SGD_FEXP_DESCRIP         VARCHAR(50) NULL,
                 PRIMARY KEY (SGD_FEXP_CODIGO)
, FOREIGN KEY (SGD_PEXP_CODIGO) REFERENCES SGD_PEXP_PROCEXPEDIENTES (SGD_PEXP_CODIGO)
);
CREATE UNIQUE INDEX IDX_FEXP_DESCRIP ON SGD_FEXP_FLUJOEXPEDIENTES (SGD_FEXP_CODIGO);
CREATE TABLE SGD_TMA_TEMAS (
SGD_TMA_CODIGO           SMALLINT NOT NULL,
SGD_PRC_CODIGO           SMALLINT NULL,
SGD_TMA_DESCRIP          VARCHAR(150) NULL,
                 PRIMARY KEY (SGD_TMA_CODIGO)
, FOREIGN KEY (SGD_PRC_CODIGO) REFERENCES SGD_PRC_PROCESO (SGD_PRC_CODIGO)
);
CREATE UNIQUE INDEX IDX_TMA_TEMAS ON SGD_TMA_TEMAS (SGD_TMA_CODIGO);
CREATE TABLE RADICADO (
RADI_NUME_RADI           BIGINT NOT NULL,
RADI_FECH_RADI           DATETIME NOT NULL,
TDOC_CODI                SMALLINT NOT NULL,
TRTE_CODI                TINYINT NULL,
MREC_CODI                TINYINT NULL,
EESP_CODI                BIGINT NULL,
EOTRA_CODI               BIGINT NULL,
RADI_TIPO_EMPR           VARCHAR(2) NULL,
RADI_FECH_OFIC           DATETIME NULL,
TDID_CODI                TINYINT NULL,
RADI_NUME_IDEN           VARCHAR(15) NULL,
RADI_NOMB                VARCHAR(90) NULL,
RADI_PRIM_APEL           VARCHAR(50) NULL,
RADI_SEGU_APEL           VARCHAR(50) NULL,
RADI_PAIS                VARCHAR(70) NULL,
MUNI_CODI                SMALLINT NULL,
CPOB_CODI                SMALLINT NULL,
CARP_CODI                SMALLINT NULL,
ESTA_CODI                TINYINT NULL,
DPTO_CODI                SMALLINT NULL,
CEN_MUNI_CODI            SMALLINT NULL,
CEN_DPTO_CODI            SMALLINT NULL,
RADI_DIRE_CORR           VARCHAR(100) NULL,
RADI_TELE_CONT           BIGINT NULL,
RADI_NUME_HOJA           SMALLINT NULL,
RADI_DESC_ANEX           VARCHAR(100) NULL,
RADI_NUME_DERI           BIGINT NULL,
RADI_PATH                VARCHAR(100) NULL,
RADI_USUA_ACTU           BIGINT NULL,
RADI_DEPE_ACTU           SMALLINT NULL,
RADI_FECH_ASIG           DATETIME NULL,
RADI_ARCH1               VARCHAR(10) NULL,
RADI_ARCH2               VARCHAR(10) NULL,
RADI_ARCH3               VARCHAR(10) NULL,
RADI_ARCH4               VARCHAR(10) NULL,
RA_ASUN                  VARCHAR(350) NULL,
RADI_USU_ANTE            VARCHAR(45) NULL,
RADI_DEPE_RADI           SMALLINT NULL,
RADI_REM                 VARCHAR(60) NULL,
RADI_USUA_RADI           BIGINT NULL,
CODI_NIVEL               TINYINT DEFAULT 1,
FLAG_NIVEL               INT DEFAULT 1,
CARP_PER                 TINYINT DEFAULT 0,
RADI_LEIDO               TINYINT DEFAULT 0,
RADI_CUENTAI             VARCHAR(20) NULL,
RADI_TIPO_DERI           TINYINT DEFAULT 0,
LISTO                    VARCHAR(2) NULL,
SGD_TMA_CODIGO           SMALLINT NULL,
SGD_MTD_CODIGO           SMALLINT NULL,
PAR_SERV_SECUE           INT NULL,
SGD_FLD_CODIGO           SMALLINT DEFAULT 0,
RADI_AGEND               TINYINT NULL,
RADI_FECH_AGEND          DATETIME NULL,
RADI_FECH_DOC            DATETIME NULL,
SGD_DOC_SECUENCIA        BIGINT NULL,
SGD_PNUFE_CODI           SMALLINT NULL,
SGD_EANU_CODIGO          TINYINT NULL,
SGD_NOT_CODI             SMALLINT NULL,
RADI_FECH_NOTIF          DATETIME NULL,
SGD_TDEC_CODIGO          SMALLINT NULL,
SGD_APLI_CODI            SMALLINT NULL,
SGD_TTR_CODIGO           SMALLINT DEFAULT 0,
USUA_DOC_ANTE            VARCHAR(14) NULL,
RADI_FECH_ANTETX         DATETIME NULL,
SGD_TRAD_CODIGO          TINYINT NULL,
FECH_VCMTO               DATETIME NULL,
TDOC_VCMTO               SMALLINT NULL,
SGD_TERMINO_REAL         SMALLINT NULL,
ID_CONT                  TINYINT DEFAULT 1,
SGD_SPUB_CODIGO          TINYINT DEFAULT 0,
ID_PAIS                  SMALLINT DEFAULT 170,
                 PRIMARY KEY (RADI_NUME_RADI)
, FOREIGN KEY (ID_CONT,ID_PAIS,DPTO_CODI,MUNI_CODI) REFERENCES MUNICIPIO (ID_CONT,ID_PAIS,DPTO_CODI,MUNI_CODI)
									   , FOREIGN KEY (SGD_NOT_CODI) REFERENCES SGD_NOT_NOTIFICACION (SGD_NOT_CODI)
									   , FOREIGN KEY (TRTE_CODI) REFERENCES TIPO_REMITENTE (TRTE_CODI)
									   , FOREIGN KEY (TDID_CODI) REFERENCES TIPO_DOC_IDENTIFICACION (TDID_CODI)
									   , FOREIGN KEY (MREC_CODI) REFERENCES MEDIO_RECEPCION (MREC_CODI)
									   , FOREIGN KEY (ESTA_CODI) REFERENCES ESTADO (ESTA_CODI)
									   , FOREIGN KEY (SGD_TDEC_CODIGO) REFERENCES SGD_TDEC_TIPODECISION (SGD_TDEC_CODIGO)
									   , FOREIGN KEY (SGD_TMA_CODIGO) REFERENCES SGD_TMA_TEMAS (SGD_TMA_CODIGO)
									   , FOREIGN KEY (SGD_MTD_CODIGO) REFERENCES SGD_MTD_MATRIZ_DOC (SGD_MTD_CODIGO)
									   , FOREIGN KEY (PAR_SERV_SECUE) REFERENCES PAR_SERV_SERVICIOS (PAR_SERV_SECUE)
									   , FOREIGN KEY (SGD_APLI_CODI) REFERENCES SGD_APLI_APLINTEGRA (SGD_APLI_CODI)
);
CREATE UNIQUE INDEX RADICADO_IDX_001 ON RADICADO (RADI_NUME_RADI, TDOC_CODI, CODI_NIVEL);
CREATE UNIQUE INDEX RADICADO_ORDEN ON RADICADO (RADI_FECH_RADI, CARP_CODI, RADI_USUA_ACTU, RADI_DEPE_ACTU, RADI_FECH_ASIG);
CREATE INDEX IDX_RADI_EESP ON RADICADO (EESP_CODI);
CREATE INDEX IDX_RADICADO_INTER ON RADICADO (MUNI_CODI, DPTO_CODI, ID_CONT, ID_PAIS);
CREATE INDEX IND_RADICADO_RADI_PATH ON RADICADO (RADI_PATH);
CREATE INDEX RADICADO_IDX_003 ON RADICADO (RADI_DEPE_RADI, SGD_EANU_CODIGO);
CREATE INDEX RADICADO_DEPENDENCIA ON RADICADO (RADI_CUENTAI);
CREATE TABLE ANEXOS (
ANEX_RADI_NUME           BIGINT NOT NULL,
ANEX_CODIGO              VARCHAR(20) NOT NULL,
ANEX_TIPO                SMALLINT NULL,
ANEX_TAMANO              INT NULL,
ANEX_SOLO_LECT           VARCHAR(1) NULL,
ANEX_CREADOR             VARCHAR(15) NULL,
ANEX_DESC                VARCHAR(512) NULL,
ANEX_NUMERO              INT NULL,
ANEX_NOMB_ARCHIVO        VARCHAR(50) NULL,
ANEX_BORRADO             VARCHAR(1) NULL,
ANEX_ORIGEN              TINYINT DEFAULT 0,
ANEX_UBIC                VARCHAR(15) NULL,
ANEX_SALIDA              TINYINT DEFAULT 0,
RADI_NUME_SALIDA         BIGINT NULL,
ANEX_RADI_FECH           DATETIME NULL,
ANEX_ESTADO              TINYINT DEFAULT 0,
USUA_DOC                 VARCHAR(14) NULL,
SGD_REM_DESTINO          TINYINT DEFAULT 0,
ANEX_FECH_ENVIO          DATETIME NULL,
SGD_DIR_TIPO             SMALLINT NULL,
ANEX_FECH_IMPRES         DATETIME NULL,
ANEX_DEPE_CREADOR        SMALLINT NULL,
SGD_DOC_SECUENCIA        BIGINT NULL,
SGD_DOC_PADRE            VARCHAR(20) NULL,
SGD_ARG_CODIGO           TINYINT NULL,
SGD_TPR_CODIGO           SMALLINT NULL,
SGD_DEVE_CODIGO          TINYINT NULL,
SGD_DEVE_FECH            DATETIME NULL,
SGD_FECH_IMPRES          DATETIME NULL,
ANEX_FECH_ANEX           DATETIME NULL,
ANEX_DEPE_CODI           VARCHAR(3) NULL,
SGD_PNUFE_CODI           SMALLINT NULL,
SGD_DNUFE_CODI           SMALLINT NULL,
ANEX_USUDOC_CREADOR      VARCHAR(15) NULL,
SGD_FECH_DOC             DATETIME NULL,
SGD_APLI_CODI            SMALLINT NULL,
SGD_TRAD_CODIGO          TINYINT NULL,
SGD_DIR_DIRECCION        VARCHAR(150) NULL,
MUNI_CODI                SMALLINT NULL,
DPTO_CODI                SMALLINT NULL,
SGD_EXP_NUMERO           VARCHAR(18) NULL,
                 PRIMARY KEY (ANEX_CODIGO)
, FOREIGN KEY (ANEX_CREADOR) REFERENCES USUARIO (USUA_LOGIN)
);
CREATE INDEX IDX_ANEX_RADI ON ANEXOS (ANEX_RADI_NUME);
CREATE UNIQUE INDEX IDX_ANEX_CODIGO ON ANEXOS (ANEX_CODIGO);
CREATE INDEX ANEXOS_IDX_001 ON ANEXOS (ANEX_CREADOR, ANEX_BORRADO, ANEX_ESTADO, SGD_DEVE_CODIGO);
CREATE INDEX IDX_ANEX_NUMERO ON ANEXOS (ANEX_NUMERO);
CREATE INDEX IDX_ANEX_RADI_SAL ON ANEXOS (RADI_NUME_SALIDA);
CREATE INDEX IDX_ANEX_DEPE_CODI ON ANEXOS (ANEX_DEPE_CODI);
CREATE TABLE ANEXOS_HISTORICO (
ANEX_HIST_ANEX_CODI      VARCHAR(20) NOT NULL,
ANEX_HIST_NUM_VER        SMALLINT NOT NULL,
ANEX_HIST_TIPO_MOD       VARCHAR(2) NOT NULL,
ANEX_HIST_USUA           VARCHAR(15) NOT NULL,
ANEX_HIST_FECHA          DATETIME NOT NULL,
USUA_DOC                 VARCHAR(14) NULL,
                 PRIMARY KEY (ANEX_HIST_ANEX_CODI, ANEX_HIST_NUM_VER)
, FOREIGN KEY (ANEX_HIST_ANEX_CODI) REFERENCES ANEXOS (ANEX_CODIGO)
									   , FOREIGN KEY (ANEX_HIST_USUA) REFERENCES USUARIO (USUA_LOGIN)
);
CREATE UNIQUE INDEX IDX_ANEX_HIST ON ANEXOS_HISTORICO (ANEX_HIST_ANEX_CODI, ANEX_HIST_NUM_VER);
CREATE TABLE HIST_EVENTOS (
DEPE_CODI                SMALLINT NOT NULL,
HIST_FECH                DATETIME NOT NULL,
USUA_CODI                BIGINT NOT NULL,
RADI_NUME_RADI           BIGINT NOT NULL,
HIST_OBSE                VARCHAR(600) NOT NULL,
USUA_CODI_DEST           BIGINT NULL,
USUA_DOC                 VARCHAR(14) NULL,
USUA_DOC_OLD             VARCHAR(15) NULL,
SGD_TTR_CODIGO           SMALLINT NULL,
HIST_USUA_AUTOR          VARCHAR(14) NULL,
HIST_DOC_DEST            VARCHAR(14) NULL,
DEPE_CODI_DEST           SMALLINT NULL
, FOREIGN KEY (DEPE_CODI) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (RADI_NUME_RADI) REFERENCES RADICADO (RADI_NUME_RADI)
);
CREATE INDEX IDX_CONSULTA ON HIST_EVENTOS (DEPE_CODI, HIST_FECH, USUA_CODI, RADI_NUME_RADI);
CREATE INDEX IDX_TIPOTRANS ON HIST_EVENTOS (SGD_TTR_CODIGO);
CREATE TABLE INFORMADOS (
RADI_NUME_RADI           BIGINT NOT NULL,
USUA_CODI                BIGINT NOT NULL,
DEPE_CODI                SMALLINT NOT NULL,
INFO_DESC                VARCHAR(600) NULL,
INFO_FECH                DATETIME NOT NULL,
INFO_LEIDO               TINYINT DEFAULT 0,
USUA_CODI_INFO           SMALLINT NULL,
INFO_CODI                BIGINT NULL,
USUA_DOC                 VARCHAR(14) NULL
, FOREIGN KEY (DEPE_CODI) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (RADI_NUME_RADI) REFERENCES RADICADO (RADI_NUME_RADI)
);
CREATE INDEX IDX_RADICADO ON INFORMADOS (RADI_NUME_RADI);
CREATE INDEX IDX_INFORMADO_USUARIO ON INFORMADOS (USUA_CODI, DEPE_CODI, INFO_FECH);
CREATE TABLE PRESTAMO (
PRES_ID                  BIGINT NOT NULL,
RADI_NUME_RADI           BIGINT NOT NULL,
USUA_LOGIN_ACTU          VARCHAR(15) NOT NULL,
DEPE_CODI                SMALLINT NOT NULL,
USUA_LOGIN_PRES          VARCHAR(15) NULL,
PRES_DESC                VARCHAR(200) NULL,
PRES_FECH_PRES           DATETIME NULL,
PRES_FECH_DEVO           DATETIME NULL,
PRES_FECH_PEDI           DATETIME NOT NULL,
PRES_ESTADO              TINYINT NULL,
PRES_REQUERIMIENTO       TINYINT NULL,
PRES_DEPE_ARCH           SMALLINT NULL,
PRES_FECH_VENC           DATETIME NULL,
DEV_DESC                 VARCHAR(500) NULL,
PRES_FECH_CANC           DATETIME NULL,
USUA_LOGIN_CANC          VARCHAR(15) NULL,
USUA_LOGIN_RX            VARCHAR(15) NULL,
                 PRIMARY KEY (PRES_ID)
, FOREIGN KEY (DEPE_CODI) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (PRES_DEPE_ARCH) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (RADI_NUME_RADI) REFERENCES RADICADO (RADI_NUME_RADI)
									   , FOREIGN KEY (USUA_LOGIN_PRES) REFERENCES USUARIO (USUA_LOGIN)
									   , FOREIGN KEY (USUA_LOGIN_ACTU) REFERENCES USUARIO (USUA_LOGIN)
);
CREATE UNIQUE INDEX IDX_PRESTAMO ON PRESTAMO (PRES_ID);
CREATE TABLE SGD_ACM_ACUSEMSG (
SGD_MSG_CODI             BIGINT NOT NULL,
USUA_DOC                 VARCHAR(14) NOT NULL,
SGD_MSG_LEIDO            SMALLINT NULL,
                 PRIMARY KEY (SGD_MSG_CODI, USUA_DOC)
, FOREIGN KEY (SGD_MSG_CODI) REFERENCES SGD_MSG_MENSAJE (SGD_MSG_CODI)
);
CREATE UNIQUE INDEX IDX_SGD_ACM_ACUSEMSG ON SGD_ACM_ACUSEMSG (SGD_MSG_CODI, USUA_DOC);
CREATE TABLE SGD_AGEN_AGENDADOS (
SGD_AGEN_FECH            DATETIME NULL,
SGD_AGEN_OBSERVACION     VARCHAR(3000) NULL,
RADI_NUME_RADI           BIGINT NOT NULL,
USUA_DOC                 VARCHAR(18) NOT NULL,
DEPE_CODI                SMALLINT NULL,
SGD_AGEN_CODIGO          INT NULL,
SGD_AGEN_FECHPLAZO       DATETIME NULL,
SGD_AGEN_ACTIVO          INT NULL
, FOREIGN KEY (RADI_NUME_RADI) REFERENCES RADICADO (RADI_NUME_RADI)
);
CREATE TABLE SGD_ANAR_ANEXARG (
SGD_ANAR_CODI            SMALLINT NOT NULL,
ANEX_CODIGO              VARCHAR(20) NULL,
SGD_ARGD_CODI            SMALLINT NULL,
SGD_ANAR_ARGCOD          SMALLINT NULL,
                 PRIMARY KEY (SGD_ANAR_CODI)
, FOREIGN KEY (ANEX_CODIGO) REFERENCES ANEXOS (ANEX_CODIGO)
									   , FOREIGN KEY (SGD_ARGD_CODI) REFERENCES SGD_ARGD_ARGDOC (SGD_ARGD_CODI)
);
CREATE UNIQUE INDEX IDX_ANAR_ANEXARG ON SGD_ANAR_ANEXARG (SGD_ANAR_CODI);
CREATE TABLE SGD_ANU_ANULADOS (
SGD_ANU_ID               SMALLINT NULL,
SGD_ANU_DESC             VARCHAR(250) NULL,
RADI_NUME_RADI           BIGINT NULL,
SGD_EANU_CODI            INT NULL,
SGD_ANU_SOL_FECH         DATETIME NULL,
SGD_ANU_FECH             DATETIME NULL,
DEPE_CODI                SMALLINT NULL,
USUA_DOC                 VARCHAR(14) NULL,
USUA_CODI                SMALLINT NULL,
DEPE_CODI_ANU            SMALLINT NULL,
USUA_DOC_ANU             VARCHAR(14) NULL,
USUA_CODI_ANU            SMALLINT NULL,
USUA_ANU_ACTA            INT NULL,
SGD_ANU_PATH_ACTA        VARCHAR(200) NULL,
SGD_TRAD_CODIGO          TINYINT NULL
, FOREIGN KEY (RADI_NUME_RADI) REFERENCES RADICADO (RADI_NUME_RADI)
									   , FOREIGN KEY (SGD_EANU_CODI) REFERENCES SGD_EANU_ESTANULACION (SGD_EANU_CODI)
);
CREATE TABLE SGD_CAUX_CAUSALES (
SGD_CAUX_CODIGO          BIGINT NOT NULL,
RADI_NUME_RADI           BIGINT NULL,
SGD_DCAU_CODIGO          SMALLINT NULL,
SGD_DDCA_CODIGO          SMALLINT NULL,
SGD_CAUX_FECHA           DATETIME NULL,
USUA_DOC                 VARCHAR(14) NULL,
                 PRIMARY KEY (SGD_CAUX_CODIGO)
, FOREIGN KEY (SGD_DCAU_CODIGO) REFERENCES SGD_DCAU_CAUSAL (SGD_DCAU_CODIGO)
									   , FOREIGN KEY (RADI_NUME_RADI) REFERENCES RADICADO (RADI_NUME_RADI)
									   , FOREIGN KEY (SGD_DDCA_CODIGO) REFERENCES SGD_DDCA_DDSGRGDO (SGD_DDCA_CODIGO)
);
CREATE UNIQUE INDEX IDX_SGD_CAUX_CAUSALES ON SGD_CAUX_CAUSALES (SGD_CAUX_CODIGO);
CREATE TABLE SGD_EXP_EXPEDIENTE (
SGD_EXP_NUMERO           VARCHAR(18) NULL,
RADI_NUME_RADI           BIGINT NULL,
SGD_EXP_FECH             DATETIME NULL,
SGD_EXP_FECH_MOD         DATETIME NULL,
DEPE_CODI                SMALLINT NULL,
USUA_CODI                SMALLINT NULL,
USUA_DOC                 VARCHAR(15) NULL,
SGD_EXP_ESTADO           TINYINT DEFAULT 0,
SGD_EXP_TITULO           VARCHAR(50) NULL,
SGD_EXP_ASUNTO           VARCHAR(150) NULL,
SGD_EXP_CARPETA          VARCHAR(30) NULL,
SGD_EXP_UFISICA          VARCHAR(20) NULL,
SGD_EXP_ISLA             VARCHAR(10) NULL,
SGD_EXP_ESTANTE          VARCHAR(10) NULL,
SGD_EXP_CAJA             VARCHAR(10) NULL,
SGD_EXP_FECH_ARCH        DATETIME NULL,
SGD_SRD_CODIGO           SMALLINT NULL,
SGD_SBRD_CODIGO          SMALLINT NULL,
SGD_FEXP_CODIGO          SMALLINT DEFAULT 0,
SGD_EXP_SUBEXPEDIENTE    INT NULL,
SGD_EXP_ARCHIVO          TINYINT NULL,
SGD_EXP_UNICON           TINYINT NULL,
SGD_EXP_FECHFIN          DATETIME NULL,
SGD_EXP_FOLIOS           VARCHAR(4) NULL,
SGD_EXP_RETE             TINYINT NULL,
SGD_EXP_ENTREPA          TINYINT NULL,
SGD_EXP_PRIVADO          TINYINT NULL
, FOREIGN KEY (DEPE_CODI) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (RADI_NUME_RADI) REFERENCES RADICADO (RADI_NUME_RADI)
);
CREATE INDEX IDX_EXP_EXP ON SGD_EXP_EXPEDIENTE (SGD_EXP_NUMERO);
CREATE INDEX IND_EXP_RADI ON SGD_EXP_EXPEDIENTE (RADI_NUME_RADI);
CREATE INDEX IDX_EXPEDIENTE_FECHA ON SGD_EXP_EXPEDIENTE (SGD_EXP_FECH);
CREATE INDEX IDX_EXPEDIENTE_DEPE_USUA ON SGD_EXP_EXPEDIENTE (DEPE_CODI, USUA_CODI);
CREATE INDEX IDX_EXPEDIENTE_USUA_DOC ON SGD_EXP_EXPEDIENTE (USUA_DOC);
CREATE INDEX IDX_EXP_TITU ON SGD_EXP_EXPEDIENTE (SGD_EXP_TITULO);
CREATE INDEX IDX_EXP_ASUN ON SGD_EXP_EXPEDIENTE (SGD_EXP_ASUNTO);
CREATE INDEX IDX_EXP_UFISI ON SGD_EXP_EXPEDIENTE (SGD_EXP_UFISICA);
CREATE INDEX IDX_EXP_ISLA ON SGD_EXP_EXPEDIENTE (SGD_EXP_ISLA);
CREATE INDEX IDX_EXP_ESTANT ON SGD_EXP_EXPEDIENTE (SGD_EXP_ESTANTE);
CREATE INDEX IDX_EXP_CAJA ON SGD_EXP_EXPEDIENTE (SGD_EXP_CAJA);
CREATE INDEX IDX_EXP_FECHAA ON SGD_EXP_EXPEDIENTE (SGD_EXP_FECH_ARCH);
CREATE INDEX IDX_EXP_FECHH ON SGD_EXP_EXPEDIENTE (SGD_EXP_FECHFIN);
CREATE INDEX IDX_EXP_FOLIO ON SGD_EXP_EXPEDIENTE (SGD_EXP_FOLIOS);
CREATE TABLE SGD_FARS_FARISTAS (
SGD_FARS_CODIGO          INT NOT NULL,
SGD_PEXP_CODIGO          INT NULL,
SGD_FEXP_CODIGOINI       INT NULL,
SGD_FEXP_CODIGOFIN       INT NULL,
SGD_FARS_DIASMINIMO      SMALLINT NULL,
SGD_FARS_DIASMAXIMO      SMALLINT NULL,
SGD_FARS_DESC            VARCHAR(100) NULL,
SGD_TRAD_CODIGO          TINYINT NULL,
SGD_SRD_CODIGO           SMALLINT NULL,
SGD_SBRD_CODIGO          SMALLINT NULL,
SGD_FARS_TIPIFICACION    TINYINT NULL,
SGD_TPR_CODIGO           INT NULL,
SGD_FARS_AUTOMATICO      INT NULL,
SGD_FARS_ROLGENERAL      INT NULL,
                 PRIMARY KEY (SGD_FARS_CODIGO)
, FOREIGN KEY (SGD_PEXP_CODIGO) REFERENCES SGD_PEXP_PROCEXPEDIENTES (SGD_PEXP_CODIGO)
);
CREATE UNIQUE INDEX IDX_FARS_FARISTAS ON SGD_FARS_FARISTAS (SGD_FARS_CODIGO);
CREATE TABLE SGD_FIRRAD_FIRMARADS (
SGD_FIRRAD_ID            BIGINT NOT NULL,
RADI_NUME_RADI           BIGINT NOT NULL,
USUA_DOC                 VARCHAR(14) NOT NULL,
SGD_FIRRAD_FIRMA         IMAGE NULL,
SGD_FIRRAD_FECHA         DATETIME NOT NULL,
SGD_FIRRAD_DOCSOLIC      VARCHAR(14) NOT NULL,
SGD_FIRRAD_FECHSOLIC     DATETIME NOT NULL,
                 PRIMARY KEY (SGD_FIRRAD_ID)
, FOREIGN KEY (RADI_NUME_RADI) REFERENCES RADICADO (RADI_NUME_RADI)
);
CREATE UNIQUE INDEX IDX_FIRRAD_FIRMARADS ON SGD_FIRRAD_FIRMARADS (SGD_FIRRAD_ID);
CREATE TABLE SGD_HMTD_HISMATDOC (
SGD_HMTD_CODIGO          INT NOT NULL,
SGD_HMTD_FECHA           DATETIME NOT NULL,
RADI_NUME_RADI           BIGINT NOT NULL,
USUA_CODI                BIGINT NOT NULL,
SGD_HMTD_OBSE            VARCHAR(600) NOT NULL,
USUA_DOC                 BIGINT NULL,
DEPE_CODI                SMALLINT NULL,
SGD_MTD_CODIGO           SMALLINT NULL,
                 PRIMARY KEY (SGD_HMTD_CODIGO)
, FOREIGN KEY (DEPE_CODI) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (RADI_NUME_RADI) REFERENCES RADICADO (RADI_NUME_RADI)
									   , FOREIGN KEY (SGD_MTD_CODIGO) REFERENCES SGD_MTD_MATRIZ_DOC (SGD_MTD_CODIGO)
);
CREATE UNIQUE INDEX IDX_HMTD_HISMATDOC ON SGD_HMTD_HISMATDOC (SGD_HMTD_CODIGO);
CREATE TABLE SGD_NTRD_NOTIFRAD (
RADI_NUME_RADI           BIGINT NOT NULL,
SGD_NOT_CODI             SMALLINT NOT NULL,
SGD_NTRD_NOTIFICADOR     VARCHAR(150) NULL,
SGD_NTRD_NOTIFICADO      VARCHAR(150) NULL,
SGD_NTRD_FECHA_NOT       DATETIME NULL,
SGD_NTRD_NUM_EDICTO      INT NULL,
SGD_NTRD_FECHA_FIJA      DATETIME NULL,
SGD_NTRD_FECHA_DESFIJA   DATETIME NULL,
SGD_NTRD_OBSERVACIONES   VARCHAR(150) NULL
, FOREIGN KEY (RADI_NUME_RADI) REFERENCES RADICADO (RADI_NUME_RADI)
);
CREATE TABLE SGD_OEM_OEMPRESAS (
SGD_OEM_CODIGO           INT NOT NULL,
TDID_CODI                TINYINT NULL,
SGD_OEM_OEMPRESA         VARCHAR(150) NULL,
SGD_OEM_REP_LEGAL        VARCHAR(150) NULL,
SGD_OEM_NIT              VARCHAR(14) NULL,
SGD_OEM_SIGLA            VARCHAR(50) NULL,
MUNI_CODI                SMALLINT NULL,
DPTO_CODI                SMALLINT NULL,
SGD_OEM_DIRECCION        VARCHAR(150) NULL,
SGD_OEM_TELEFONO         VARCHAR(50) NULL,
ID_CONT                  TINYINT DEFAULT 1,
ID_PAIS                  SMALLINT DEFAULT 170,
                 PRIMARY KEY (SGD_OEM_CODIGO)
, FOREIGN KEY (ID_CONT,ID_PAIS,DPTO_CODI,MUNI_CODI) REFERENCES MUNICIPIO (ID_CONT,ID_PAIS,DPTO_CODI,MUNI_CODI)
									   , FOREIGN KEY (TDID_CODI) REFERENCES TIPO_DOC_IDENTIFICACION (TDID_CODI)
);
CREATE UNIQUE INDEX IDX_OEM_OEMPRESAS ON SGD_OEM_OEMPRESAS (SGD_OEM_CODIGO);
CREATE INDEX SQG_BUSQ_EMPRESA ON SGD_OEM_OEMPRESAS (SGD_OEM_OEMPRESA, SGD_OEM_SIGLA);
CREATE INDEX SGD_BUSQ_NIT ON SGD_OEM_OEMPRESAS (SGD_OEM_NIT);
CREATE TABLE SGD_DIR_DRECCIONES (
SGD_DIR_CODIGO           BIGINT NOT NULL,
SGD_DIR_TIPO             SMALLINT NOT NULL,
SGD_OEM_CODIGO           INT NULL,
SGD_CIU_CODIGO           INT NULL,
RADI_NUME_RADI           BIGINT NULL,
SGD_ESP_CODI             INT NULL,
MUNI_CODI                SMALLINT NULL,
DPTO_CODI                SMALLINT NULL,
SGD_DIR_DIRECCION        VARCHAR(150) NULL,
SGD_DIR_TELEFONO         VARCHAR(50) NULL,
SGD_DIR_MAIL             VARCHAR(50) NULL,
SGD_SEC_CODIGO           BIGINT NULL,
SGD_TEMPORAL_NOMBRE      VARCHAR(150) NULL,
ANEX_CODIGO              BIGINT NULL,
SGD_ANEX_CODIGO          VARCHAR(20) NULL,
SGD_DIR_NOMBRE           VARCHAR(150) NULL,
SGD_DOC_FUN              VARCHAR(14) NULL,
SGD_DIR_NOMREMDES        VARCHAR(1000) NULL,
SGD_TRD_CODIGO           TINYINT NULL,
SGD_DIR_TDOC             TINYINT NULL,
SGD_DIR_DOC              VARCHAR(14) NULL,
ID_PAIS                  SMALLINT DEFAULT 170,
ID_CONT                  TINYINT DEFAULT 1,
                 PRIMARY KEY (SGD_DIR_CODIGO)
, FOREIGN KEY (SGD_CIU_CODIGO) REFERENCES SGD_CIU_CIUDADANO (SGD_CIU_CODIGO)
									   , FOREIGN KEY (RADI_NUME_RADI) REFERENCES RADICADO (RADI_NUME_RADI)
									   , FOREIGN KEY (SGD_OEM_CODIGO) REFERENCES SGD_OEM_OEMPRESAS (SGD_OEM_CODIGO)
									   , FOREIGN KEY (ID_CONT,ID_PAIS,DPTO_CODI,MUNI_CODI) REFERENCES MUNICIPIO (ID_CONT,ID_PAIS,DPTO_CODI,MUNI_CODI)
);
CREATE INDEX IDX_SGD_DIR ON SGD_DIR_DRECCIONES (SGD_DIR_CODIGO);
CREATE INDEX SGD_DIR_DRECCIONES_IDX_001 ON SGD_DIR_DRECCIONES (SGD_DIR_TIPO, RADI_NUME_RADI, SGD_ESP_CODI);
CREATE INDEX IDX_SGD_DIR_OEM_CODIGO ON SGD_DIR_DRECCIONES (SGD_OEM_CODIGO);
CREATE INDEX IDX_DIR_CIU_CODIGO ON SGD_DIR_DRECCIONES (SGD_CIU_CODIGO);
CREATE INDEX IDX_DIR_INT ON SGD_DIR_DRECCIONES (MUNI_CODI, DPTO_CODI, ID_PAIS, ID_CONT);
CREATE INDEX IDX_SGD_DIR_NOMBRE ON SGD_DIR_DRECCIONES (SGD_DIR_NOMBRE);
CREATE INDEX IDX_SGD_DOC_FUN ON SGD_DIR_DRECCIONES (SGD_DOC_FUN);
CREATE INDEX IDX_SGD_DIR_NOMREMDES ON SGD_DIR_DRECCIONES (SGD_DIR_NOMREMDES);
CREATE INDEX IDX_SGD_DIR_DOC ON SGD_DIR_DRECCIONES (SGD_DIR_DOC);
CREATE TABLE SGD_PNUN_PROCENUM (
SGD_PNUN_CODI            SMALLINT NOT NULL,
SGD_PNUFE_CODI           SMALLINT NULL,
DEPE_CODI                SMALLINT NULL,
SGD_PNUN_PREPONE         VARCHAR(50) NULL,
                 PRIMARY KEY (SGD_PNUN_CODI)
, FOREIGN KEY (DEPE_CODI) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (SGD_PNUFE_CODI) REFERENCES SGD_PNUFE_PROCNUMFE (SGD_PNUFE_CODI)
);
CREATE UNIQUE INDEX IDX_PNUN_PROCENUM ON SGD_PNUN_PROCENUM (SGD_PNUN_CODI);
CREATE TABLE SGD_RENV_REGENVIO (
SGD_RENV_CODIGO          INT NOT NULL,
SGD_FENV_CODIGO          INT NULL,
SGD_RENV_FECH            DATETIME NULL,
RADI_NUME_SAL            BIGINT NULL,
SGD_RENV_DESTINO         VARCHAR(150) NULL,
SGD_RENV_TELEFONO        VARCHAR(50) NULL,
SGD_RENV_MAIL            VARCHAR(150) NULL,
SGD_RENV_PESO            VARCHAR(10) NULL,
SGD_RENV_VALOR           VARCHAR(10) NULL,
SGD_RENV_CERTIFICADO     TINYINT NULL,
SGD_RENV_ESTADO          TINYINT NULL,
USUA_DOC                 BIGINT NULL,
SGD_RENV_NOMBRE          VARCHAR(100) NULL,
SGD_REM_DESTINO          TINYINT DEFAULT 0,
SGD_DIR_CODIGO           BIGINT NULL,
SGD_RENV_PLANILLA        VARCHAR(8) NULL,
SGD_RENV_FECH_SAL        DATETIME NULL,
DEPE_CODI                SMALLINT NULL,
SGD_DIR_TIPO             SMALLINT DEFAULT 0,
RADI_NUME_GRUPO          BIGINT NULL,
SGD_RENV_DIR             VARCHAR(100) NULL,
SGD_RENV_DEPTO           VARCHAR(30) NULL,
SGD_RENV_MPIO            VARCHAR(30) NULL,
SGD_RENV_TEL             VARCHAR(20) NULL,
SGD_RENV_CANTIDAD        SMALLINT DEFAULT 0,
SGD_RENV_TIPO            TINYINT DEFAULT 0,
SGD_RENV_OBSERVA         VARCHAR(200) NULL,
SGD_RENV_GRUPO           BIGINT NULL,
SGD_DEVE_CODIGO          TINYINT NULL,
SGD_DEVE_FECH            DATETIME NULL,
SGD_RENV_VALORTOTAL      VARCHAR(14) DEFAULT '0',
SGD_RENV_VALISTAMIENTO   VARCHAR(10) DEFAULT '0',
SGD_RENV_VDESCUENTO      VARCHAR(10) DEFAULT '0',
SGD_RENV_VADICIONAL      VARCHAR(14) DEFAULT '0',
SGD_DEPE_GENERA          SMALLINT NULL,
SGD_RENV_PAIS            VARCHAR(30) DEFAULT 'Colombia'
, FOREIGN KEY (DEPE_CODI) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (SGD_DEVE_CODIGO) REFERENCES SGD_DEVE_DEV_ENVIO (SGD_DEVE_CODIGO)
									   , FOREIGN KEY (SGD_DIR_CODIGO) REFERENCES SGD_DIR_DRECCIONES (SGD_DIR_CODIGO)
);
CREATE INDEX IND_RENV_CODIGO ON SGD_RENV_REGENVIO (SGD_RENV_CODIGO);
CREATE INDEX IND_RENV_RADI_SAL ON SGD_RENV_REGENVIO (SGD_FENV_CODIGO, RADI_NUME_SAL, DEPE_CODI);
CREATE INDEX IND_RENV_FECH ON SGD_RENV_REGENVIO (SGD_RENV_FECH);
CREATE INDEX IND_RENV_FECH_SAL ON SGD_RENV_REGENVIO (SGD_RENV_FECH_SAL);
CREATE INDEX IND_RENV_GRUPO ON SGD_RENV_REGENVIO (SGD_RENV_GRUPO);
CREATE TABLE SGD_TMD_TEMADEPE (
ID                       INT NOT NULL,
SGD_TMA_CODIGO           SMALLINT NOT NULL,
DEPE_CODI                SMALLINT NOT NULL,
                 PRIMARY KEY (ID)
, FOREIGN KEY (DEPE_CODI) REFERENCES DEPENDENCIA (DEPE_CODI)
									   , FOREIGN KEY (SGD_TMA_CODIGO) REFERENCES SGD_TMA_TEMAS (SGD_TMA_CODIGO)
);
CREATE UNIQUE INDEX IDX_TMD_TEMADEPE ON SGD_TMD_TEMADEPE (ID);